### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by sheldhur** [cdimascio/express-openapi-validator#10]
Hi. 

`openapi-request-validator` is fast, because that use `Ajv`. `Ajv` compiles schemas into simple fast validation functions. This should be done once, but you create new `OpenAPIRequestValidator` object upon each request (https://github.com/cdimascio/express-openapi-validator/blob/master/src/middlewares/openapi.request.validator.ts#L65).

You not only lost perfomance, but also made it worse. Cache `OpenAPIRequestValidator` when it is created.

**Comment by cdimascio** [comment]
will fix this. thanks for the issue!

**Comment by cdimascio** [comment]
This is fixed in v1.2.1.
