### ISSUE TITLE
Routes with glob caused error starting from 5.3.7

### ISSUE THREAD

**Issue by imsamurai** [cdimascio/express-openapi-validator#1019]
**Describe the bug**
Route like `/some/(.*)` caused

```
TypeError: Unexpected ( at 9, expected END: https://git.new/pathToRegexpError
    at Iter.consume (/project/node_modules/express-openapi-validator/node_modules/path-to-regexp/dist/index.js:123:15)
    at consume (/project/node_modules/express-openapi-validator/node_modules/path-to-regexp/dist/index.js:179:16)
    at parse (/project/node_modules/express-openapi-validator/node_modules/path-to-regexp/dist/index.js:183:20)
    at /project/node_modules/express-openapi-validator/node_modules/path-to-regexp/dist/index.js:294:74
    at Array.map (<anonymous>)
    at pathToRegexp (/project/node_modules/express-openapi-validator/node_modules/path-to-regexp/dist/index.js:294:25)
    at lookupRoute (/project/node_modules/express-openapi-validator/dist/middlewares/openapi.metadata.js:73:65)
    at /project/node_modules/express-openapi-validator/dist/middlewares/openapi.metadata.js:17:25
    at /project/node_modules/express-openapi-validator/dist/openapi.validator.js:126:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 
```
starting from version 5.3.7

**To Reproduce**

add route to spec and go /some
```
  /some/(.*):
    get:
      responses:
        200:
          description: OK
```

**Actual behavior** 
Error

**Expected behavior**
Validation success

**Comment by cdimascio** [comment]
unfortunately, this is a change in path-to-regex. see https://github.com/pillarjs/path-to-regexp?tab=readme-ov-file#express--4x. bullet 3 impacts your case. however, you should be able to handle this in an alternative manner, using the suggestion in bullet 1

**Comment by cdimascio** [comment]
note that there are mechanism to match wild card paths. see this [test](https://github.com/cdimascio/express-openapi-validator/blob/2d33d0af590c2c1782652efb2614839bd37d1643/test/wildcard.path.params.spec.ts) and accompanying [spec](https://github.com/cdimascio/express-openapi-validator/blob/2d33d0af590c2c1782652efb2614839bd37d1643/test/resources/wildcard.path.params.yaml)

another example...

you can match paths using the following:

```json
            paths: {
                '/some/{wildcard}*': {
                    parameters: [
                        {
                            name: 'wildcard',
                            in: 'path',
                            required: true,
                            schema: {
                                type: 'string',
                            },
                        },
                    ],
                    get: {
                        responses: {
                            '200': {
                                description: 'OK',
                            },
                        },
                    },
                },
            }
```

```javascript
   .get('/api/some/:wildcard(*)', (req, res) => {
        const wildcard = req.params.wildcard;
        console.log(`Wildcard: ${wildcard}`);
        res.status(200).send(`Matched wildcard: ${wildcard}`);
    }),
```

then `GET .get(`/some/test/stuff`)` will match and arbitrary path, like `/test/stuff`

**Comment by cdimascio** [comment]
im going to close this out given there are options to handle this case. please re-open if i've not captured your use case

**Comment by imsamurai** [comment]
Sorry for delay, you ask about use case. 
I have the route /doc where swagger web ui are hosted. 
Web ui needs to load js, css, etc: /doc/somescript.js.
Because i don't control this lib and some files may be changed i need to allow them all: /doc/(.*).

Maybe you can do some backward compatibility in validator? Because this is major change, not path version.
