### ISSUE TITLE
Error message produced for missing content-type is weird

### ISSUE THREAD

**Issue by henhal** [cdimascio/express-openapi-validator#114]
If a path requires a request body of type `application/json` but the request has no `Content-Type` header set, express-openapi-validator will produce the following error: 

415 - `unsupported media type not_provided`

This is hard to understand - `not_provided` seems to be used as an internal constant for missing `Content-Type` but this should perhaps not be returned outside of the module? A better error message would be:

415 - `media type not specified`

**Comment by cdimascio** [comment]
@henhal thanks for the issue. the message is fixed in 2.14..4

**Comment by waynebloss** [comment]
I got this message also when I posted to my API without a body, on accident.
