### ISSUE TITLE
Rejecting unknown query parameters should be optional

### ISSUE THREAD

**Issue by rgcunha** [cdimascio/express-openapi-validator#133]
Hi,

Would it be possible to make unknown query parameter validation optional?
https://github.com/cdimascio/express-openapi-validator/blob/master/src/middlewares/openapi.request.validator.ts#L109

Problem:
We have an API for a react-native app that needs to support multiple client versions. Some of the legacy versions still send query params which are no longer specified in the latest API spec as such we need to bypass the unknown query param validation.

Unfortunately there doesn't seem to be a way to make this validation optional atm.

Thanks

**Comment by cdimascio** [comment]
@rgcunha yes. this is a reasonable request. we'll plan to provide this option to the request validator

**Comment by cdimascio** [comment]
hi @rgcunha, give `2.16.0` a try.
You can set
```javascript
 validateRequests: {
   allowUnknownQueryParameters: true
 }
```
to allow unknown query params to pass validation

**Comment by rgcunha** [comment]
tested. works as expected. thanks @cdimascio 👌

**Comment by WilliamStewart** [comment]
Any way of doing this for a specific endpoint instead of globally?

**Comment by cdimascio** [comment]
@WilliamStewart Currently, there is not. It's something to consider. Feel free to open an issue and perhaps a description of the use case.
I'd argue that better to keep this behavior consistent (choose one or the other for the entirety of the API) in order to alleviate confusion amongst the APIs users.
