### ISSUE TITLE
Supporting libraries

### ISSUE THREAD

**Issue by Gi60s** [cdimascio/express-openapi-validator#134]
You may be interested in the [OpenAPI Enforcer](https://www.npmjs.com/package/openapi-enforcer) that is essentially a set of helper methods that would make what you're doing very easy. It already has a lot of the features that are being requested within your issues. It is thoroughly documented and tested, so check it out.

Full disclaimer, I wrote this library so I am biased. I also wrote an [express middleware](https://www.npmjs.com/package/openapi-enforcer-middleware) using the OpenAPI Enforcer that seems to do a lot of the same things as this library. You might want to check it out to see how easy it is to write a middleware around the OpenAPI Enforcer.

Either way, good luck!

**Comment by cdimascio** [comment]
Thanks will have a lot ok
