### ISSUE TITLE
Support writeOnly + required combination

### ISSUE THREAD

**Issue by cdimascio** [cdimascio/express-openapi-validator#149]
Notes below copied from @Haruki-Mortis [readonly issue](https://github.com/cdimascio/express-openapi-validator/issues/145)
**Documentation definition**
**writeOnly** (The writeOnly functionality has not been checked yet)
>Relevant only for Schema "properties" definitions. Declares the property as "write only". Therefore, it MAY be sent as part of a request but SHOULD NOT be sent as part of the response. If the property is marked as writeOnly being true and is in the required list, the required will take effect on the request only. A property MUST NOT be marked as both readOnly and writeOnly being true. Default value is false.

related issue: https://github.com/cdimascio/express-openapi-validator/issues/145

**Comment by mamatela** [comment]
Any progress on this? It would be so awesome to have this feature. It stands between me being able to use the same schema for get and post operations vs having to create separate almost-duplicates.

**Comment by na2793** [comment]
I am also curious about this. I really need this feature.

**Comment by Mike-J-W** [comment]
Commenting to say this feature is still desired. And that a pull request exists for it, https://github.com/cdimascio/express-openapi-validator/pull/756, if @cdimascio could review it.

**Comment by cdimascio** [comment]
available in v5.1.5. thanks @pdhau

**Comment by cdimascio** [comment]
@all-contributors add @pdhau  for code and test
