### ISSUE TITLE
Endless loop caused by json-schema-ref-parser

### ISSUE THREAD

**Issue by scriptify** [cdimascio/express-openapi-validator#151]
Hello!

For some strange reason I yet not know, the "bundle" method of the class "$RefParser" seems to cause an endless loop on line 16: https://github.com/cdimascio/express-openapi-validator/blob/b8e34304ab5c2821a51c986e43b4b6ae4db51d05/src/framework/json.ref.schema.ts#L16

As I am the first one with this issue, maybe it is caused by my setup.

Those are my dependencies:

```json
{
    "@typegoose/typegoose": "^6.1.5",
    "cors": "^2.8.5",
    "express": "^4.17.1",
    "express-openapi-validator": "^2.17.2",
    "express-session": "^1.17.0",
    "mongoose": "^5.7.12",
    "openid-client": "^3.8.3",
    "react": "^16.11.0",
    "react-dom": "^16.11.0",
    "swagger-ui-express": "^4.1.2",
    "webpack-pwa-manifest": "^4.0.0",
    "workbox-webpack-plugin": "^3.6.3",
    "yamljs": "^0.3.0"
  }
```

I also tried using different OpenAPI specs (also the one in the tests directory of this repo), with the same result.

Maybe it's a dependecy conflict somehow?

**Comment by scriptify** [comment]
Update: I don't know why yet, but it has to do something with the database connection I'm establishing, which seems very strange. If I establish the MongoDB connection _after_ calling **install**, it works just fine. Otherwise, it keeps blocking the whole thread. I am not sure why this is happening.

**Comment by cdimascio** [comment]
@scriptify this change is part of >2.17.0 to enable support spec splitting via $refs. the change has been live for 2days, so other may run into this.

based on the code snippet you provided, this is coming from the use of package `deasync`. i used this package (despite the risks) to synchronously resolve all `$refs` in a multiple file spec. i did this in order to preserve the current api. using `deasync` to force synchronicity appears to be the root of this problem. i'm not sure if there is a good solution to fix this as is. it may require handling the initial parse asynchronously, which ultimately means the api for express-openapi-validator must change and a new major version must be rolled.

in any case, i'll start investigating that path.
if you find a workaround, please let me know. i'll certainly document it or provide a patch. 
if you find a solution, PRs are always welcome!

**Comment by cdimascio** [comment]
Also, if you can provide a simple express app that demonstrates the problem, I'll dig in.

**Comment by cdimascio** [comment]
@scriptify i put together a super simple test with mongodb. i was able to setup a connection prior to installing middleware

here is the full server source code

```
const express = require('express');
const path = require('path');
const cookieParser = require('cookie-parser');
const bodyParser = require('body-parser');
const logger = require('morgan');
const http = require('http');
const MongoClient = require('mongodb').MongoClient;
const OpenApiValidator = require('express-openapi-validator').OpenApiValidator;
const app = express();

// 1. Install bodyParsers for the request types your API will support
app.use(bodyParser.urlencoded());
app.use(bodyParser.text());
app.use(bodyParser.json());

app.use(logger('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));

const spec = path.join(__dirname, 'openapi.yaml');
app.use('/spec', express.static(spec));

// Connect to MongoDB before installing OpenApiValidator
const client = MongoClient.connect('mongodb://localhost:27017/example', {
  useUnifiedTopology: true,
})
  .then(client => client.db())
  .catch(e => {
    console.error(e);
    process.exit(1);
  });

// Load some dummy data
client
  .then(db =>
    db
      .collection('example')
      .insertMany([{ id: 2, name: 'sparky' }, { id: 3, name: 'spot' }]),
  )
  .catch(e => {
    console.error(e);
    process.exit(1);
  });

//  Install the OpenApiValidator on your express app
new OpenApiValidator({
  apiSpec: './example.yaml',
}).install(app);

app.get('/v1/pets', function(req, res, next) {
  client
    .then(db =>
      db
        .collection('example')
        .find()
        .toArray(),
    )
    .then(pets => res.json(pets))
    .catch(next);
});

app.use((err, req, res, next) => {
  console.error(err);
  res.status(err.status || 500).json({
    message: err.message,
    errors: err.errors,
  });
});

const server = http.createServer(app);
server.listen(3000);
console.log('Listening on port 3000');

module.exports = app;
```

You can use the spec.yaml from [here](https://github.com/cdimascio/express-openapi-validator/blob/master/example/example.yaml)

**Comment by cdimascio** [comment]
in any case, i'm still interested in finding out how to repro the issue you are hitting

**Comment by scriptify** [comment]
I'll create a minimal example today after work. Thanks in the mean time!

**Comment by scriptify** [comment]
I've put together a minimal example, you can find it here: https://github.com/scriptify/express-openapi-validator-issue-151
I tried to mimic the development environment I'm using as precise as possible, sorry for the many unneeded dependencies I make you install. Instructions can be found in the README. Would love to contribute if we're able to find the issue!

**Comment by cdimascio** [comment]
i gave this a try, but i'm not seeing the issue

![image](https://user-images.githubusercontent.com/4706618/69767195-263c6b00-1149-11ea-9dc0-5f021fe46056.png)

I tried with
node `v12.7.0` and `10.14.1`

**Comment by scriptify** [comment]
Switching to node `v12.7.0` resolved the issue! Before I was using `v12.13.1`. I never thought that this could be the cause. So this very version of `deasync` could be incompatible with `v12.13.1`, or it's an issue with node itself.

**Comment by scriptify** [comment]
Maybe it's due to the fact that deasync is using very low level building blocks and directly modifying the behaviour of the event loop.
To better understand why deasync is needed here: It is needed because the `bundle` method of `json-schema-ref-parser` is asynchronous, right? So the only remaining solutions here would be reweiting this library in a synchronous manner, or making the setup process itself asynchronous. Don't you think it would be possible to make it asynchronous without a breaking change? So that validation kicks in a short amount of time _after_ initialization (then of course, there's the risk of a few API calls not being validated in the worst case)?

**Comment by cdimascio** [comment]
It is possible to make the parse async. I have a  working version in a local branch. It will cause a a breaking API change, thus will need a major version bump. I certainly plan to make the change. Still exploring. I'll make the branch available, would live the feedback

**Comment by scriptify** [comment]
In which branch can it be found? So I'll close this issue now, thanks for your help!

**Comment by cdimascio** [comment]
@scriptify you can find the async version on the branch, `async_` [here](https://github.com/cdimascio/express-openapi-validator/tree/async_1)

Here is an [example](https://github.com/cdimascio/express-openapi-validator/blob/async_1/example/app.js#L34) of what an app might look like.

Note that `install` method would return a promise, then user-defined routes are then defined once the install promise resolves.

This is one possible option, I'm still investigating other approaches.

**Comment by scriptify** [comment]
Looks good. This could be even more convenient when using toplevel await.

Would it also be possible to `install` the validator alongside, without having to wait until everything was set up?

**Comment by cdimascio** [comment]
Yeah, agreed, aop level await is nice; almost no difference in usage. The order of middleware matters, thus the validator needs to be set up prior your routes
