### ISSUE TITLE
allowReserved not validated properly.

### ISSUE THREAD

**Issue by ckeboss** [cdimascio/express-openapi-validator#158]
Just ran into this. May or may not be an issue with AJV.

**Comment by cdimascio** [comment]
thanks @ckeboss. could\ you provide an example showing the input, the expected result, and the actual result.

**Comment by cdimascio** [comment]
> Determines whether the parameter value SHOULD allow reserved characters, as defined by RFC3986 :/?#[]@!$&'()*+,;= to be included without percent-encoding. This property only applies to parameters with an in value of query. The default value is false.

**Comment by cdimascio** [comment]
@ckeboss  this is fixed in v3.6.0
