### ISSUE TITLE
Multi multer options

### ISSUE THREAD

**Issue by yskeat** [cdimascio/express-openapi-validator#160]
I have multiple file upload API to handle different file use case.
Each API will have its own storage and file filter options.
Is there a way to achieve it in express-openapi-validator?

**Comment by cdimascio** [comment]
@yskeat currently, the validator takes one set of multi opts which means they cannot be configured per endpoint.

one way to get the behavior you desire would be to use `ignorePaths`. By using `ignorePaths`, you can disable the validator on the particular routes that require specialized handling.

`ignorePaths` gives you a way to indirectly handle your use case, however, if you have thoughts on how to we might better support your use case, please share your ideas here.

**Comment by yskeat** [comment]
@cdimascio  I just notice that v3 is been release. Congratulation.

I yet to try out v3 so I assume most of the code is the same as v2. 

Here is my suggestion on how to solve my problem. 

Since multer option cannot be configure per endpoint, how about if multer option is null or undefined, ignore installMultipathMiddleware? It doesn't make any sense for me to go through an empty multer option for all multipath/form-data request.

Suggest to modify src/index.ts line 76 as below

> if (this.options.multerOpts) this.installMultipartMiddleware(app, context);

This is tested and work well for my next path level multer middleware to perform its storage and fileFilter check

**Comment by cdimascio** [comment]
This sounds reasonable, though I'd suggest a separate option to disable the middleware or potentially have multerOpts also take the string disable.

**Comment by faroceann** [comment]
@cdimascio  For my use case, `multerOpts` should definitely have the option to disable, or be disabled by default.  ` express-openapi-validator` doesn't do automatic body  parsing, why should it do automatic file upload handling?

**Comment by yskeat** [comment]
As for my experience, multipath/form-data or multer covered less then 2% of my REST API. 

If I am going to use express-openapi-validator in all of my every microservices, I strongly prefer multerOpts to opt in instead of opt out, at least it save 1 line of my code to 
multerOpts: false || null || "disable".

**Comment by cdimascio** [comment]
i agree. the reason for opt-out is backward compatibility. given its been live 1 day. i'm willing to consider changing it to `opt-in`. I agree that is a better design.

Perhaps,  we introduce a new top-level property e.g.

```javascript
fileUpload: {
   multerOpts: {...}
}
```

if `fileUpload` is present the upload middleware is enabled, if not, its disabled. 
thoughts?

**Comment by yskeat** [comment]
So far I only tried pull request in private projects in Gitlab.
I never participate in public project pull request but I don't mind to give it a try. 
Please do guide me if anything goes wrong.

**Comment by cdimascio** [comment]
sure thing. will gladly provide any guidance you need. feel free to reach out on our [gitter](https://gitter.im/cdimascio-oss/community) channel too.

**Comment by cdimascio** [comment]
@yskeat enabling the default file uploader is optional in v3.4.1. it can be disabled with the following

```javascript
fileUploader: false
```

**Comment by cdimascio** [comment]
@faroceann fyi ^
file upload can now be disabled

**Comment by yskeat** [comment]
Thanks for the info. Will check it out later
