### ISSUE TITLE
Issue with deasync from version 2.17.0

### ISSUE THREAD

**Issue by gonenduk** [cdimascio/express-openapi-validator#162]
I have a problem with mongodb connection after I started to use version 2.17.0 and above.
In my base app, I first connect to the DBs and then initialise the routes.
The mongo db connection is successful, but then it gets a disconnection with a refuse error and a exception is thrown. The last 3 lines of the stack are:
`    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:14)
    at Function.module.exports.loopWhile (/Users/gonen/repos/basejs/node_modules/deasync/index.js:71:23)
    at Object.bundle (/Users/gonen/repos/basejs/node_modules/express-openapi-validator/dist/framework/json.ref.schema.js:13:19)`

Since this is something difficult to reproduce, I suggest you git clone my base app repository from gonenduk/basejs, run npm install and npm start.

With version 2.16.1:
Everything works well like before.

With version 2.17.0 and above:
You get the errors mentioned above.

For more info, we can chat over it.

**Comment by cdimascio** [comment]
Thanks @gonenduk. There are a few others having issues with deasync. I’m looking to remove the dependency, however removing it means an api change. Would you you mind having a look at the proposal here. https://github.com/cdimascio/express-openapi-validator/pull/161
Would like your feedback

**Comment by cdimascio** [comment]
@gonenduk i've released an alpha version of v3. please give it a try. it makes `deasync` optional. it must be explicitly installed and is only needed if using the lib synchronously

The new dep is: "express-openapi-validator": "^3.0.0-alpha.1"

See the alpha readme [here](https://github.com/cdimascio/express-openapi-validator/tree/async_1)

**Comment by gonenduk** [comment]
I tried the new beta and it seems to work fine!
Didn't find any new issues.

**Comment by cdimascio** [comment]
fixed in 3.0.0
