### ISSUE TITLE
validateSecurity: false is still resulting in a 401 

### ISSUE THREAD

**Issue by thetumper** [cdimascio/express-openapi-validator#180]
I have a security definition applied globally (all routes):

<pre>
  security:
    - bearerAuth: []
</pre>

And, this in components:

<pre>
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
</pre>

With the validator installed like this:

<pre>
new OpenApiValidator({
  apiSpec: leadsAPISpecJSON,
  validateSecurity: false
}).install(app);
</pre>

When I do a GET on my /ping route, I receive a 401 "Authorization header with scheme 'Bearer' required".

Shouldn't the validateSecurity: false be preventing that?

**Comment by cdimascio** [comment]
Can you verify that you are using the latest version
This should work.

The example/app.js can be used to demonstrate this. 

**Disable security**

```javascript
new OpenApiValidator({
  apiSpec,
  validateSecurity: false
})
```

```shell
λ curl -X POST http://localhost:3000/v1/pets -d '{"name": "test","type": "dog" }' -H 'content-type: application/json'

{"id":4,"name":"test","type":"dog"}%                                                                                                                                                        
```

**Using default options** 

```javascript
new OpenApiValidator({
  apiSpec,
})
```

```shell
λ curl -X POST http://localhost:3000/v1/pets -d '{"name": "test","type": "dog" }' -H 'content-type: application/json'

{"message":"'X-API-Key' header required","errors":[{"path":"/v1/pets","message":"'X-API-Key' header required"}]}%   
```

**Comment by thetumper** [comment]
Ack.  Sorry!  I still had version 2.15.1.  This was only added in latest (3.1.1).

**Comment by cdimascio** [comment]
👍 note v3.1.1 has some breaking changes. have a look at the readme. simply upgrading will cause problems. 

the validator api is now async by default. if you choose to continue to use a blocking `install` (similar to v2), you must explicitly call `installSync(..)`. There are some gotchas about a sync installl that had caused users some pain, hence the change in v3. 

anyway, have a peek at the readme to ensure a smooth upgrade

**Comment by thetumper** [comment]
Thanks so much!  I did notice the async install, and got that working with promise.then, as in the example.  Working fine now.
