### ISSUE TITLE
Issue with some $ref 

### ISSUE THREAD

**Issue by jy95** [cdimascio/express-openapi-validator#183]
Hello,

I saw it is possible to split specifications into multiple files. 
I tried to split mine ( [from my master branch](https://raw.githubusercontent.com/SourceCodeOER/sourcecode_api/master/api.yml) ) into a [separate branch](https://github.com/SourceCodeOER/sourcecode_api/tree/delete_exercises_and_tags) : the ["main file"](https://raw.githubusercontent.com/SourceCodeOER/sourcecode_api/delete_exercises_and_tags/api.yml) and the [rest](https://github.com/SourceCodeOER/sourcecode_api/tree/delete_exercises_and_tags/openapi)

( I didn't forget to escape special characters like explained in Swagger : https://swagger.io/docs/specification/using-ref/ or in this [old open api v2 tutorial](https://apihandyman.io/writing-openapi-swagger-specification-tutorial-part-8-splitting-specification-file/#modifying-paths-references) )

To test if the specifications are correct (and work as expected), I used the following commands explained in my readme : 

![image](https://user-images.githubusercontent.com/9306961/70936970-ccdaa400-2043-11ea-90f7-25daf49e45d8.png)

The validator seems to accept the specifications : 

![image](https://user-images.githubusercontent.com/9306961/70937119-0e6b4f00-2044-11ea-8d00-5ede2c93a746.png)

However, some endpoints like /auth/login and /auth/register no longer work and send me an error of this type : 

![image](https://user-images.githubusercontent.com/9306961/70936746-3efeb900-2043-11ea-824b-8fd43dd95caa.png)

Any idea what caused this problem? The path seems to be recognized in other tools ( like the OpenAPI (Swagger) Editor extension in Visual Studio Code ) 

![image](https://user-images.githubusercontent.com/9306961/70937657-efb98800-2044-11ea-8de8-2f2069a527d3.png)

Thanks

**Comment by jy95** [comment]
@cdimascio I maybe found the explanation and it is not funny :( 
https://github.com/APIDevTools/json-schema-ref-parser/issues/44

**Comment by cdimascio** [comment]
@jy95, merged your PR. the new option for the json schema ref parser is available in `v3.5.0`
