### ISSUE TITLE
Security handler for 'Bearer' does not exist

### ISSUE THREAD

**Issue by AlekseyMko** [cdimascio/express-openapi-validator#191]
Hello, 
I am working with Google cloud functions and they use "Bearer" token  in the Authorization header.

I have got an exception when tried to implement the validateSecurity hendler

[cloud.google.com/functions/docs/securing/authenticating](cloud.google.com/functions/docs/securing/authenticating)

Many thanks

**Comment by cdimascio** [comment]
@AlekseyMko we do support Bearer authentication.
See OpenAPI spec for [Bearer](https://swagger.io/docs/specification/authentication/bearer-authentication/) auth
Here is an example in this project's tests:

https://github.com/cdimascio/express-openapi-validator/blob/master/test/resources/security.top.level.yaml#L95
https://github.com/cdimascio/express-openapi-validator/blob/master/test/resources/security.top.level.yaml#L60

**Comment by AlekseyMko** [comment]
Thank you,
It does work!

**Comment by cdimascio** [comment]
Woop!
