### ISSUE TITLE
path templates matched incorrectly

### ISSUE THREAD

**Issue by eden** [cdimascio/express-openapi-validator#214]
According to the OpenAPI spec, path templates should match specific to general: http://spec.openapis.org/oas/v3.0.2#path-templating-matching

Currently, if you define an API with the following paths, the request validation improperly throws a method not allowed validation error if one defines a schema that isn't supported by the other.

```
/pets/{petId}
/pets/mine
```

If you swap the order when you specify it in the openapi document, the validation works without issue. However, this order shouldn't matter.

**Comment by cdimascio** [comment]
thanks for the issue, @eden. this should be resolved in v3.6.2. please give it a try

**Comment by eden** [comment]
Works great! Thanks for the quick fix.
