### ISSUE TITLE
Sending empty response passes response check successfully

### ISSUE THREAD

**Issue by TomHartogs** [cdimascio/express-openapi-validator#219]
For one of my paths I have defined a response schema for express-openapi-validator (EOV) to validate. However, I noticed that no error was thrown by EOV when I send a response using `res.sendStatus(201)` without a body. Sending a response with `res.json()` also does not throw an error. Sending a response with `res.json({})` does throw an error.

This might be done by choice, but I was unable to find any comments about this. I would assume that if I define a required response, the validator would throw an error if I do not send a response body at all.

**Comment by cdimascio** [comment]
@TomHartogs thanks for the issue. fixed in `3.6.5`.
