### ISSUE TITLE
fileUploader doesn't fully replace multerOpts

### ISSUE THREAD

**Issue by JacobLey** [cdimascio/express-openapi-validator#222]
Hello,

I think I've run into an issue regarding the change from `multerOpts` to `fileUploader`.

https://github.com/cdimascio/express-openapi-validator/pull/205/files
With the recent version `3.6.3` when I provide `multerOpts` (unchanged usage, but according to README it is acceptable for now) files get cached locally instead of forwarded onto the provided storage (I was providing a `storage` attribute, but thats getting farther into `multer`'s settings).

I tried changing the variable name to `fileUploader` but still behavior is not desired.

Looking through the code, its looks like my issue comes from this line: https://github.com/cdimascio/express-openapi-validator/blob/master/src/index.ts#L153

Essentially I think `multerOpts` should be replaced with `fileUploader` to match the rest of the logic: https://github.com/cdimascio/express-openapi-validator/blob/master/src/index.ts#L153

Does that make sense?
Opened a PR to help highlight the issue and hopefully fix: https://github.com/cdimascio/express-openapi-validator/pull/221

**Comment by cdimascio** [comment]
thanks for the ticket and the fix. merged in `3.6.6`
