### ISSUE TITLE
Option to accept unhandled routes

### ISSUE THREAD

**Issue by Cactusbone** [cdimascio/express-openapi-validator#224]
For routes not defined in specs, I'd like to be able to not have a failure, for examples when routes are added after OpenApiValidator.install call (in my case asynchronously), or to be able to have multiple specs with overlapping baseUrl (in multiple OpenApiValidator instances), to sort code to my liking.

It this already possible ?

**Comment by cdimascio** [comment]
@Cactusbone thanks for the question. 
there are few options. 
1. you can instruct the validator to ignore certain routes via a regex. have a look at the `ignorePaths` option. any routes matched by the regex will be ignored by the validator 
2. have a look at the [multiple validators/specs example](https://github.com/cdimascio/express-openapi-validator#Example-Multiple-Validators-and-API-specs)
3. (not exactly what you're looking for) any routes not defined under `basePath` are ignored by the validator. 

let me know if this helps or if you run into any issues. certainly, want me ensure this scenario works for you. also feel free to reach on our [gitter](https://gitter.im/cdimascio-oss/community) channel

**Comment by Cactusbone** [comment]
@cdimascio thanks for the answer

I'm trying to add openapi-validator gradually in an already existing project, so we have a lot of existing routes, and we'd like to only use openapi-validator for specific routes, without breaking our usual REST route organization, mutiple validators example use a distinct baseUrl for each validator instance. I'll try overlapping routes when I'll need them though :)

Right now i'll use basePath, and try to call install after every other route is configured

**Comment by cdimascio** [comment]
@Cactusbone That should work. `ignorePaths` is also your friend. With `ignorePaths` you should construct the regex to match all routes you plan to ignore.

closing this issue for now. If you find the existing functionality doesn't suit your needs, please re-open and we'll look to provide a better solution.

thanks for your interest in the project

**Comment by Cactusbone** [comment]
ignorePaths is kinda hard to maintain though, watchPath regexp or a flag to allow unknown routes would be easier to use in my case
