### ISSUE TITLE
pathParams

### ISSUE THREAD

**Issue by mathewmeconry** [cdimascio/express-openapi-validator#233]
This typing has from my point of view the wrong type assigned:
```typescript
pathParams: string[];
```

should be
```typescript
pathParams: { [index: string]: string };
```

during debugging the `pathParams` is an object:
![image](https://user-images.githubusercontent.com/4057473/74540254-bff10880-4f3f-11ea-8349-e2332fc7e499.png)

File where I found it: 
https://github.com/cdimascio/express-openapi-validator/blob/461e960bb36661fdcdb8957f53f324911f370390/src/framework/types.ts#L401

I'm happy to open a pull request if you accept this as an issue.

**Comment by cdimascio** [comment]
@mathewmeconry thanks. i think you're right. please open a PR. thanks a lot!

**Comment by mathewmeconry** [comment]
@cdimascio  here you go :)
