### ISSUE TITLE
Missing parameter name at 8

### ISSUE THREAD

**Issue by stanleynguyen** [cdimascio/express-openapi-validator#238]
I'm using express-openapi-validator on macOS Catalina like below
```js
const openapiValidator = new ExpressValidator(opts)
openapiValidator.install(app)
```
but I'm getting this error on all of my requests
![Screenshot 2020-02-21 at 10 22 00 AM](https://user-images.githubusercontent.com/12974927/75001623-831f9700-5494-11ea-9da1-e3bb883ae475.png)

**Comment by cdimascio** [comment]
@stanleynguyen based on the trace, it seems to be failing in the call to pathToRegex [here](https://github.com/cdimascio/express-openapi-validator/blob/master/src/middlewares/openapi.metadata.ts#L47)

could you can modify the file referenced in the image below, the console.log the parameters passed to `pathToRegex`. this info may help me to understand the issue without a reproducible example
![image](https://user-images.githubusercontent.com/4706618/75085232-0a045c00-54f5-11ea-943f-c1161112ca95.png)

also, if can you can create a simple example that demonstrates the issue this will be most helpful. perhaps post it in a github repo. i'll certainly have a look

**Comment by stanleynguyen** [comment]
@cdimascio thank you for the prompt response.
Turns out I have invalid character in my route under `servers`, which is `expressRoute /Xendit/:{cookiecutter.service_name}/0.0.1/`
