### ISSUE TITLE
Encoding of space in query

### ISSUE THREAD

**Issue by johandalabacka** [cdimascio/express-openapi-validator#241]
Hi

I have a problem. axios sends queries there space is encoded as + like

http://localhost:8080/abd/lucat/employees?search=Fredrik+Johansson&limit=10

and this results in an error from express-openapi-validator:

```json
{"path":".query.search","message":"Parameter 'search' must be url encoded. It's value may not contain reserved characters."}
```

The line here includes + as a reserved character in queries
https://github.com/cdimascio/express-openapi-validator/blob/master/src/middlewares/parsers/req.parameter.mutator.ts#L18

axios seems to working on this because even thou + is a standard is it several systems which don't handle this. https://github.com/axios/axios/pull/2563

So how will you handle this?

**Comment by johandalabacka** [comment]
I worked around it by defining my own paramsSerializer:

```js
axios.defaults.paramsSerializer = (params) => {
    return Object.entries(params).map(x => `${encodeURIComponent(x[0])}=${encodeURIComponent(x[1])}`)
      .join('&')
  }
})
```

**Comment by cdimascio** [comment]
Your workaround is the best way to handle this.

The `+` character is a reserved character according to [RFC3986](https://tools.ietf.org/html/rfc3986), thus the validator is doing the right thing. 

At this point in time, I think it makes sense to close this and wait for the axios fix. 
Thoughts?

**Comment by jazzzz** [comment]
Is it really invalid? This is how every browser encodes a space when submitting a form, like with this form:

```html
<form>
  <input name="foo" value="a b">
  <button>Submit</button>
</form>
```

**Comment by Cactusbone** [comment]
> 
> 
> Your workaround is the best way to handle this.
> 
> The `+` character is a reserved character according to [RFC3986](https://tools.ietf.org/html/rfc3986), thus the validator is doing the right thing.
> 
> At this point in time, I think it makes sense to close this and wait for the axios fix.
> Thoughts?

axios won't be fixing it. https://github.com/axios/axios/issues/1111

**Comment by cdimascio** [comment]
In order to use reserved characters, you can set the `allowReserved: true` on the query parameter. 
https://swagger.io/docs/specification/describing-parameters/

**Comment by johandalabacka** [comment]
Very good. Thank you 😊❤️
