### ISSUE TITLE
coerceTypes is all or nothing

### ISSUE THREAD

**Issue by jtinbergen** [cdimascio/express-openapi-validator#243]
When you do not want coerceTypes to correct malformed payloads sent into your API you MUST mark your openAPI parameters as String or no API call will succeed.

/test/{number}/detail/{number2}

This call will fail since parameters are always strings (you do not have a choice!).

Ideally you would want to always coerce parameters when possible (since you don't have a choice in sending them as string) and let the body/payload optionally be coerced if desired.

**Comment by cdimascio** [comment]
thanks @jtinbergen. good point. we'll look into it

**Comment by cdimascio** [comment]
this sounds like the same problem as described in https://github.com/cdimascio/express-openapi-validator/issues/249#issuecomment-636499628. thoughts?

**Comment by cdimascio** [comment]
@jtinbergen i've put together [PR](#387 ) which attempts to solve these issues via a behavioral change.
- type coercion will will continue to apply to query, path,and header params
- type coercion will not apply to request bodies.

as a result, the `coerceTypes` option becomes a bit ambiguous. i plan to deprecate the property as it's not clear what its behavior should be. all or nothing is not desired. there is an argument for two options, but believe, the behavior that makes the most sense is what i've outlined above. with this behavior, i don't know that a type coercion option is needed.

thoughts?

**Comment by cdimascio** [comment]
fixed in `v4.1.0`
