### ISSUE TITLE
loadSpec() issues, asynchronous middleware registration

### ISSUE THREAD

**Issue by faroceann** [cdimascio/express-openapi-validator#252]
In some cases it may not ideal to have `express-openapi-validator` load and dereference the provided Open API spec on its own. 

Would it be feasible for us to add support for a string or buffer argument in place of `filePath` in [loadSpec()](https://github.com/faroceann/express-openapi-validator/blob/master/src/framework/index.ts#L76) which skips the JSON scheme dereferencing and calls to `fs`?

**Comment by cdimascio** [comment]
Can you describe your use case?
Also please provide some detail about the behavior you are experiencing.
 
As for providing a buffer or string, the validator already accepts a string, however it will still dereference it. We could potentially can add an option to instruct the validator to skip the dereference phase (by adding a disable option to the refParser option). This could ensure the spec is used as is, however if the spec provided ends up having refs, it might lead to unexpected behaviors.

**Comment by cdimascio** [comment]
@faroceann thanks for the issue. Can you describe the issue in a bit more detail. We could potentially add an additional option to $refParser that disables the dereference phase. That being said I’d like to understand your issue in a bit more depth. Thanks!

**Comment by faroceann** [comment]
Hey @cdimascio, there are two things going on here, the first is that we compile and deference our OpenAPI spec ourself, so we don't need those phases to occur. 

The second thing, which is more nuanced, is that the way `express-openapi-validator` temporarily changes the CWD and loads the file using an absolute path is not ideal for my scenario. I need to resolve and load the spec file in our own modules, and would prefer to simply pass a string representing our JSON OpenAPI spec to `express-openapi-validator`, rather than a path.

**Comment by cdimascio** [comment]
@faroceann I've created a PR #252. The PR it continue to support the two methods of providing an api spec; that being the ability to provide either a path or JSON object as`apiSpec`

Additionally, the enhancement adds a new option to `$refParser`. `$refParser` can now be set to false, thus disabling the dereference/bundle and instead keeps the object as-is or loads the file using `fs` as-is

**Comment by faroceann** [comment]
Thank you @cdimascio for putting together the PR. 

It wasn't clear to me upon first look that this library supports providing a JSON object as `apiSpec`. 

While I still think having the option skip dereferencing feels useful, and I tested your PR and it worked, I found a different root cause of my original issue. Loadspec() was not working for me due to `deasync` – I did not realize there was a peer dependency required to run `installSync()`. 

For my scenario, `installSync()` is necessary since I need the `express-openapi-validator` middleware to install before I register my other middlewares. I have found that if I do not use `installSync()`, this library will not return errors to the client, since my other middleware ends up registering before `express-openapi-validator`. 

Having the peer dependency was a bit of a surprise, but I can see that `deasync` is essentially a native module and that is why you opted to declare it as a peer dep. 

Is there a better way you can think of to approach this, without the need for a native module like `deasync`? Is registering the middleware asynchronously a pattern you imagine keeping in the library in the long term?

**Comment by faroceann** [comment]
Update: I took a look and found out why doing this synchronously would be challenging, and why you chose `deasync`.  😄It looks the `json-schema-ref-parser` dependency is strictly async. 

One much better approach  I found was to use `await` 
``` 
await new OpenApiValidator({
  apiSpec: spec,
  validateRequests: true,
  validateResponses: false
}).install()
``` 

Instead of a non-awaited `.installSync()`. This allows my middlewares to bootstrap in the order I want.

**Comment by cdimascio** [comment]
Yes. Deaync is there for folks who were using it in v2. There are a lot of gotchas with deasync, hence with v3 we did continue to support it, but it is not recommended. Certainly use install() and either promises or async /await.

**Comment by cdimascio** [comment]
All being said, is the option to disable the ref parser no longer necessary for your use case?

**Comment by faroceann** [comment]
Yes, it's no longer necessary   – Thank you so much for your help
