### ISSUE TITLE
Difference from swagger-express-validator

### ISSUE THREAD

**Issue by komikoni** [cdimascio/express-openapi-validator#276]
I used to use swagger-express-validator when using OAS V2.
https://github.com/gargol/swagger-express-validator

It was very convenient, but it did not support V3.
So I found express-openapi-validator.

Unfortunately Some features of swagger-express-validator are missing.

- requestValidationFn
- responseValidationFn
- ajvRequestOptions
- ajvResponseOptions

Any ideas for implementing similar functionality to these?

express-openapi-validator is a very useful library.
Thank you very much.

**Comment by cdimascio** [comment]
Can u describe some of the features your looking for in more detail?

Some notes which may be relevant:

With respect to Ajv ootions, a number of the most relevant Ajv options can be tweaked via the validator's options object. See the README to view the validators option. There should be good coverage for the more frequent customizations. Note that if there is a particular Ajv option that you are looking for, please let us know. We can work to incorporate it, if it makes sense. Also, please provide a relevant use case along with that request.

As for request and response validation functions,  express-openapi-validator automatically performs validation and propagates the error to the standard express middleware error function.

From, there u can access the error object and manipulate it as you like, thus there is no need for an additional custom handler function.

In cases where u might want to manually handle an error, u can use the `ignorePaths` option to opt matching routes out of validation 

Hope this helps. Look forward to your comments

**Comment by komikoni** [comment]
I'm sorry I can't reply.

You're right The error object that can be parsed is returned, so you can process it freely.
There is no problem.

I decided to use express-openapi-validator for a cool project.

I'll send you some coffee! (Is it coming now? ^ _ ^)
Also give feedback.

**Comment by cdimascio** [comment]
@komikoni thanks so much!!
