### ISSUE TITLE
Support cookie based security validation?

### ISSUE THREAD

**Issue by tkarls** [cdimascio/express-openapi-validator#280]
I have an API and added both Bearer token authentication as well as support for sessions with cookies. But now the openapi validater never ever complain about missing credentials if I have them both listed in the security array.

It works as expected when I only use bearer auth (getting 401 and error message if no bearer token is present). But as soon as I add the cookie based auth to the security array the validator doesn't complain about missing tokens or missing cookies for that matter.

It took me a while to pinpoint but I think the problem is that cookie auth was never implemented and then it always treat that as successful even if no cookie is present. See below.

https://github.com/cdimascio/express-openapi-validator/blob/03ba8d619e8b4bcb39f1e42f7eab4c5e164cf1b6/src/middlewares/openapi.security.ts#L246

**Comment by cdimascio** [comment]
@tkarls Yep. We need to get this implemented. 
Would you mind providing the relevant snippet from your API spec

**Comment by cdimascio** [comment]
initial cookie auth support: https://github.com/cdimascio/express-openapi-validator/commit/b7d7afc5fa3f2fdf3ec4560ae0db4b80aa26903e

**Comment by cdimascio** [comment]
@tkarls please give `v3.12.5` a try. let me know if suits your needs.

**Comment by cdimascio** [comment]
@tkarls this is fixed in the latest version, please re-open if you still have issues. Thank you!

**Comment by tkarls** [comment]
@cdimascio Wow, this was quick 😁

I will test the latest version during the day!
Many thanks!

**Comment by tkarls** [comment]
@cdimascio 
I have tested it in my project now and it works!
Only small thing left would be that it only returns the error of the first validation that failed. So if I don't send in any cookie nor any token I get an error message that complains about only one of them (the first that failed) which is the first I list in the openapi spec.

Which is different from other request validations where I get an array of all errors encountered back.

However, since with the auth errors it is sufficient to have ONE of them correct it might not be the best approach to return them as an array either. Since that can be interpreted as all of them need to be fulfilled.

Anyway, the important thing is that the validation is working. So thanks again for your rapid fix :) !

**Comment by cdimascio** [comment]
thanks @tkarls. i'll create a ticket for the errors. will be good to have the same representation
