### ISSUE TITLE
Multi versioned api specification - only first version being initiated 

### ISSUE THREAD

**Issue by gudbrand3** [cdimascio/express-openapi-validator#281]
**Describe the bug**
It seems that when trying to load multiple api specifications for validation of different versions the await new OpenApiValidator only recognises the first version provided in the array of multiple.

**To Reproduce**
**app.js**
```
const { OpenApiValidator } = require('express-openapi-validator');
const { openAPIValidatorRouter } = require('./openapi/validator')

// helm, cors, bodyparser

async function main() {
        const versions = [1,2,3];
    
        for (let v of versions) {
            let apiSpec = path.join(__dirname,"openapi",`v${v}.yaml`);
            await new OpenApiValidator({
              apiSpec,
            }).install(app)
            openAPIValidatorRouter(app, v++)
          } 
}
main()
```

**app/validator.js**
```
async function openAPIValidatorRouter(app, version) {
    app.get(`/api/v${version}/pets`,function(req,res,next){     //simple route for test
        res.json([{id:1,name:'max'},{id:2,name:'scott'}])
    })    

    app.use(require('./../routes'));                                              //all routes

    app.use((err, req, res, next) => {
      // format error
      res.status(err.status || 500).json({
        message: err.message,
        errors: err.errors,
      });
    });
  }

module.exports = { openAPIValidatorRouter }
```

**app/routes.js**
```
const express = require('express');
const router = express.Router();

router.use('/', require('./api/generic'));
router.use('/api/v1', require('./api/v1/v1.js'));
router.use('/api/v2', require('./api/v2/v2.js'));
router.use('/api/v3', require('./api/v3/v3.js'));

module.exports = router;
```

**Actual behavior** 
The validator always works for the first version defined in the array of "versions". 
As described in example with 
`array const versions = [1,2,3] - version 1 specification validation works`

If changing array to 
`array const versions = [2,3,1] - version 2 specification validation works `

Same for 3 and x

**Expected behavior**
Instances of validator should load for all versions defined in versions array.

**Examples and context**
see above

**Comment by cdimascio** [comment]
@gudbrand3 two things:
1. I noticed a mistake in the example provided in the README. The same bug is present in app which is at least contributing to the problem.
```javascript
// change this
openAPIValidatorRouter(app, v++)
// to this
openAPIValidatorRouter(app, v)
```
2. I've updated the README and also created a new complete [example](https://github.com/cdimascio/express-openapi-validator/tree/master/examples/2-standard-multiple-api-specs)

Please give this a try. Let me know how it goes

**Comment by cdimascio** [comment]
@gudbrand3  i'm closing this seeing the problem once the app code is fixed i.e. bullet 1. above. Also, the new example works.

Please reopen if you continue to see the issue after applying the fixes. Thanks!
