### ISSUE TITLE
Type Coercion

### ISSUE THREAD

**Issue by richdouglasevans** [cdimascio/express-openapi-validator#29]
## What's The Issue?

The validator is mutating request body payloads.

We think we'd like to be able to configure the validator to do validation _only_.

## Where?

[See here](): specifically, `coerceTypes: true`

```ts
    const aoav = new middlewares.RequestValidator(this.context.apiDoc, {
      coerceTypes: true,
      removeAdditional: true,
      useDefaults: true,
    });
```

With `coerceTypes: true` — the hardcoded value — we see a property being sent in the request body being transformed from the boolean literal `true` to the string literal `"true"`.

```json
"majorReferenceWork": true . // before validation

"majorReferenceWork": "true" // after validation
```

When I change the module so that `coerceTypes: false` then the boolean property remains a boolean literal. This is our desired behaviour.

## How To Reproduce?

I can, and will, add a reproducible test case… but I wanted to have a quick discussion about this behaviour before doing that because you might tell me I'm doing something dumb 😄 

## Fix?

I don't think the current behaviour is wrong and `coerceTypes` defaulting to `true` is fine: but, it'd be nice if we could turn this off via a configuration parameter.

Totally open to other suggestions.

**Comment by cdimascio** [comment]
Thanks @richdouglasevans. I'll have a look at providing an option coerceTypes.

**Comment by cdimascio** [comment]
@richdouglasevans 
i put together a test to try out your case. as far as i can tell it works correctly

Given the following spec for Pet (which is used in the POST request below)

```yaml
    NewPet:
      required:
        - name
      properties:
        name:
          type: string
        tag:
          type: string
        is_cat:
          type: boolean
```

I created the following test
In this case, `is_cat` as specified as a boolean above, however it is passed in the request as a string and is thus properly type coerced
```
     it.only('should coerce the string 'true' to the boolean true', async () =>
        request(app)
          .post(`${basePath}/pets`)
          .send({
            name: 'test',
            is_cat: 'true', 
          })
          .expect(200)
          .then(r => {
            expect(r.body.is_cat).to.be.a('boolean');
          }));
```

Note, in the test above, specifying the string `true` is properly coerced to `boolean`

I also created this test to ensure the boolean `true` will remain a boolean if defined as such in the spec

```
  it.only('should keep the boolean true as a boolean', async () =>
        request(app)
          .post(`${basePath}/pets`)
          .send({
            name: 'test',
            is_cat: true, 
          })
          .expect(200)
          .then(r => {
            expect(r.body.is_cat).to.be.a('boolean');
          }));
```

If these cases do not match yours, please let me know.

Also, as a sanity check, please ensure the type for `majorReferenceWork` is defined with type `boolean` and not `string`

**Comment by richdouglasevans** [comment]
Carmine you're a ⭐️ Thanks for the speedy reply.

Annoyingly, I'm unable to supply a failing example using the `pets` schema. The issue manifests consistently in the schema I'm using on this work project but I just can't get the same behaviour elsewhere.

Let me close this ticket because I need to spend some time understanding what, specifically, is causing the issue in my environment: if I can create a failing example using the `pets` schema I'll open another ticket.

👍

**Comment by cdimascio** [comment]
np. i've added a couple tests around coercion in case we find a need for this. https://github.com/cdimascio/express-openapi-validator/pull/35/commits/3126ef98e798de778348ef986f9302c8a40a3858

**Comment by cdimascio** [comment]
@richdouglasevans ive added the ability to disable type coercion. The option is described in the ready. Hope this helps

**Comment by richdouglasevans** [comment]
I saw that Carmine, cheers! I'll be testing it next week at work 👌
