### ISSUE TITLE
Consider dividing installation into two steps for schema processing and middleware

### ISSUE THREAD

**Issue by rhalukongor** [cdimascio/express-openapi-validator#295]
**Is your feature request related to a problem? Please describe.**
Current API forces the function that builds the routes to be async since the installation is async. (I know there is the sync version but if I understand correctly, it may be problematic).

**Describe the solution you'd like**
I would prefer installation to be made in two steps:
1. An async `validator.setup(options) => middleware`
2. A sync `app.use(middleware)`.

This way would lead to somewhat cleaner code, e.g:
```
validator.setup(options)
  .then(middleware => ({  middleware }))
  .then(options => ({ ...options, app: createApp(options) })
  .then(options => startServer(options))
  .then(server => log.info("server started"))
```
**Describe alternatives you've considered**
No alternatives considered

**Additional context**
That's it

**Comment by cdimascio** [comment]
I am experimenting with converting this to standard express middleware [here](https://github.com/cdimascio/express-openapi-validator/pull/351)

**Comment by cdimascio** [comment]
closing this in favor of #352 - use standard express middleware
@rhalukongor please give `v4.0.0-alpha.1` a try. I would love to get your feedback. Thanks!
