### ISSUE TITLE
Route matching does not take into account method

### ISSUE THREAD

**Issue by ckeboss** [cdimascio/express-openapi-validator#296]
**Describe the bug**
2 routes are defined:

```
router.get('/foo/:id')
router.patch('/foo/:slug')
```

PATCH /foo/foo-bar

security will not find the schema because it will be looking in the route `/foo/:id` and only a GET is defined, so a 405 will be thrown.

**To Reproduce**
See above

**Actual behavior** 
See above

**Expected behavior**
I believe the lookupRoute should take into account if the schema exists. It looks like it's intentional right now to not check the schema. Reason behind this?

I will take write up a test to reproduce

**Comment by cdimascio** [comment]
the issue may be the fact the `/foo/:id` and `/foo/:slug` have different path paramater names

it should work if the path parameter name is the same e.g.
```yaml
  /api_key/:id:
    get:
      responses:
        '200':
          description: OK
        '401':
          description: unauthorized
    patch:
      responses:
        '200':
          description: OK
        '401':
          description: unauthorized
```

looks like have different parameter names for the same route is causing the problem.

**Comment by cdimascio** [comment]
@ckeboss i don't believe what you are looking for is currently supported by openapi. it certainly is not for swagger 2. it appears to be an open discussion for OAS3.
- https://github.com/swagger-api/swagger-editor/issues/854
- https://github.com/OAI/OpenAPI-Specification/issues/1635

**Comment by cdimascio** [comment]
closing this out as its not supported by oas3. please reopen if/when this or similar use cases become supported by the spec. also, if there are existing tools that provide this functionality, it will be good to list those. perhaps, we can borrow some of those ideas

**Comment by davidediak** [comment]
@cdimascio Could you please provide a link to the related specification rule?

I've tried searching in OAS specs, but no luck yet.
