### ISSUE TITLE
Responses statuses documentation

### ISSUE THREAD

**Issue by suchy** [cdimascio/express-openapi-validator#298]
Hi, is there any list of status codes express-openapi-validator respond with?

Didn't find that in docs and I'd like to be sure what and in which case I'm going to send to user.

Also I'd like to map all errors to distinguish bugs and operational errors.

Thanks! :)

**Comment by cdimascio** [comment]
@suchy Thanks. I'll look to get something into the README. 
For now, here's the shortlist:

**Requests:**
`400` validation errors
`401` security authentication error e.g. missing api-key, Authorization header, etc
`404` a path is not declared in the API spec
`405` if a path exists, but does not have a schema declared for the method

**Responses**
`500` - for all validation errors

**Comment by cdimascio** [comment]
readme has been updated with this information

**Comment by suchy** [comment]
Thanks for quick reaction! :pizza:
