### ISSUE TITLE
Throw custom Error instead of simple Error object

### ISSUE THREAD

**Issue by efabris** [cdimascio/express-openapi-validator#299]
Actually in the request validation process an error is thrown in this way:

`throw validationError(errorCode, req.path, description);`

This approach does not allow to use the power of "istanceof" instruction in the error middleware to detect the error type and add type based logic. The unique way to detect the error type is to check err.status.

A possible solutions could be the use of class and throwing with the "new" operator.

Example:

```
throw validationError(
    400,
    `.query.${q}`,
    `Unknown query parameter '${q}'`,
);
```

Could become:

```
throw new BadRequestError(
    400,
    `.query.${q}`,
    `Unknown query parameter '${q}'`,
);
```

In this way in the error middleware it's possibile to detect the error in this way:

```
if (err instanceof BadRequestError) {
    console.warn(`Caught Bad Request Error for ${req.path}:`, err.fields)
    return res.status(422).json({
      message: 'Validation Failed',
      ....
    })
  }
```

I have seen that the "ono" library is used in the code to get a similar result but it doesn't seem to work with instance checking.

If you want I can work on a possibile implementation of the feature and submit a pull request.

**Comment by cdimascio** [comment]
Available in v3.14.0
