### ISSUE TITLE
Response validation

### ISSUE THREAD

**Issue by agrakhov** [cdimascio/express-openapi-validator#30]
Thanks for this useful lib.
I have small question - is it possible to validate response? I've tried to return payload not matching oas spec schema and seems like there is no error.

**Comment by cdimascio** [comment]
response validation is not yet implemented, but it is planned

**Comment by cdimascio** [comment]
the response validation work has begun. you can follow it here.
https://github.com/cdimascio/express-openapi-validator/pull/51

**Comment by cdimascio** [comment]
@agrakhov response validation beta is available in version 2.1.0. The readme describes how to enable it.
