### ISSUE TITLE
query array - how do i allow reserved characters in query string

### ISSUE THREAD

**Issue by PavlenkoXX** [cdimascio/express-openapi-validator#300]
I am using OpenAPI 3.0 and I created swagger get route with query param:

```
{
        "in": "query",
        "name": "test",
        "style": "form",
        "explode": false,
        "schema": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
```

and using swagger-ui-express on UI everything good and I can send array of values to endpoint 

`/endpoint?test=1,2,3`

but validator brings me error

`Parameter 'test' must be url encoded. It's value may not contain reserved characters.`

what's wrong with that?

**Comment by cdimascio** [comment]
@PavlenkoXX , in your openapi spec, set `allowReserved: true`, if you want to allow reserved characters.
Below is a snippet from the OpenAPI doc

from https://swagger.io/docs/specification/serialization/
> Additionally, the allowReserved keyword specifies whether the reserved characters :/?#[]@!$&'()*+,;= in parameter values are allowed to be sent as they are, or should be percent-encoded. By default, allowReserved is false, and reserved characters are percent-encoded. For example, / is encoded as %2F (or %2f), so that the parameter value quotes/h2g2.txt will be sent as quotes%2Fh2g2.txt

**Comment by cdimascio** [comment]
https://www.ietf.org/rfc/rfc2396.txt

> 2.2. Reserved Characters

>Many URI include components consisting of or delimited by, certain special characters. These characters are called "reserved", since their usage within the URI component is limited to their reserved purpose. If the data for a URI component would conflict with the reserved purpose, then the conflicting data must be escaped before forming the URI.
>
>  reserved    = ";" | "/" | "?" | ":" | "@" | "&" | "=" | "+" |  "$" | ","
>
>The "reserved" syntax class above refers to those characters that are allowed within a URI, but which may not be allowed within a particular component of the generic URI syntax
