### ISSUE TITLE
Query parameters validation

### ISSUE THREAD

**Issue by blaisn** [cdimascio/express-openapi-validator#31]
I have downloaded and install the example app and run it as is, except for the port (3000->3001)
Issuing "GET http://localhost:3001/v1/pets?limit=10&test=two" passes successfully and gives expected result.
But issuing "GET http://localhost:3001/v1/pets?limit=10&test=two&foo=baz" does not give any error and still gives the same result with the undefined parameter "foo". Normal?

**Comment by cdimascio** [comment]
@blaisn Thanks for the issue. This is the expected behavior. That being said it is worth considering an option to trigger a validation error if an unexpected query param is provided

**Comment by cdimascio** [comment]
@blaisn query param validation is coming soon https://github.com/cdimascio/express-openapi-validator/pull/49

**Comment by cdimascio** [comment]
@blaisn this behavior is provided in v2.0.0. it is currently the default and only option.

I'll likely add an option to enable an opt-out

**Comment by marrasen** [comment]
I have a query parameter of type object and the default serialization format (style=form and explode=true). The query then contains the name of the properties in the object as query parameters, but I get a "400 Unknown query parameter". Is serialized objects not supported or am I doing something wrong?
