### ISSUE TITLE
Not found path not work with express router

### ISSUE THREAD

**Issue by sergebesson** [cdimascio/express-openapi-validator#310]
**Describe the bug**
if using an express router instead of app express, a path not defined does not return the Not Found error

**Examples and context**
example with code bug_openapi.js
```javascript
const express = require("express");
const { OpenApiValidator } = require("express-openapi-validator");

async function execute() {

	const router = express.Router();
	await new OpenApiValidator({
		apiSpec: {
			openapi: "3.0.0",
			info: { version: "1.0.0", title: "test bug OpenApiValidator" },
			servers: [{ url: "http://localhost:8080/api/" }],
			paths: {
				"/": {get: {responses: {200: {description: "home api"}}}}
			},
		},
	}).install(router);

	router.get("/", (req, res) => res.status(200).send("home api\n"));
	router.get("/notDefined", (req, res) => res.status(200).send("url api not defined\n"));

	const app = express();
	app.get('/', (req, res) => res.status(200).send("home\n"));
	app.use("/api", router);

	app.listen(3000);
	console.log("server start port 3000");

}

execute().catch((error) => console.error(error.stack));
```
`node bug_openapi.js` to start server
`curl http://localhost:3000/api/notDefined` return 200 - url api not defined.
however, a path is not defined in apiSpec. The return should have been 404 Not Found

**Comment by cdimascio** [comment]
@sergebesson thanks for the issue. will get this fixed

**Comment by cdimascio** [comment]
@sergebesson this is fixed in `v3.16.1`

**Comment by cdimascio** [comment]
thank you for the reproducible code snippet. i used it as the test [here](https://github.com/cdimascio/express-openapi-validator/blob/master/test/router.spec.ts#L46)

**Comment by sergebesson** [comment]
thank you for fix :-)
