### ISSUE TITLE
allowUnknownQueryParameters:false will be skipped if query parameter is not defined in OAS

### ISSUE THREAD

**Issue by komikoni** [cdimascio/express-openapi-validator#311]
**Describe the bug**

When defining the query parameter schema, undefined parameters will result in an error, but if undefined, all will be accepted.

https://github.com/cdimascio/express-openapi-validator/blob/master/src/middlewares/openapi.request.validator.ts#L168

**Expected behavior**

If the schema is undefined, instead of skipping it, check for the absence of query parameters.

However, since it is different from the current behavior, it seems to have a great impact on existing users.
Is it possible by writing something on the OAS side?

**Comment by cdimascio** [comment]
@komikoni thanks for the issue. This is a bug. It is fixed in `v3.15.0`.
