### ISSUE TITLE
Response validation does not follow #ref

### ISSUE THREAD

**Issue by gicuuu3** [cdimascio/express-openapi-validator#313]
**Describe the bug**

Specifications written using the `responses` `component` structure are not parsed correctly for the response validation.

**To Reproduce**

define a response as

```json
...
"responses": {
  "200": {
    "$ref": "#/components/responses/ResponseBody"
  }
}

....

"components": {
  "responses": {
    "ResponseBody": {
        "description": "...",
        "content": {}
    }
  }
}
```

**Actual behavior** 

The response validation throws `500` with `no schema defined for status code '200' in the openapi spec`

**Expected behavior**

To follow the ref down to the defined schema.

**Examples and context**

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#responses-object

I think the code where the issue starts is here, but I might be wrong since I don't really know your codebase well.

https://github.com/cdimascio/express-openapi-validator/blob/master/src/middlewares/openapi.response.validator.ts#L200

Thanks for your time!

**Comment by cdimascio** [comment]
@gicuuu3 this should be resolved in `v3.15.1`. please reopen if you continue to have issues
