### ISSUE TITLE
Is there a changelog?

### ISSUE THREAD

**Issue by saimonmoore** [cdimascio/express-openapi-validator#321]
**Is your feature request related to a problem? Please describe.**
It's hard to upgrade without a changelog 🙏 

**Describe the solution you'd like**
Any kind of changelog for each published version would be really helpful.

**Comment by cdimascio** [comment]
this is a good idea. i will look into automated options. if you have recommendations, please let me know

**Comment by saimonmoore** [comment]
We use https://github.com/conventional-changelog/conventional-changelog + https://www.npmjs.com/package/commitizen. The combination works very well.

**Comment by cdimascio** [comment]
@saimonmoore a changelog now exists. thanks for the tip!

**Comment by cdimascio** [comment]
currently, its not perfectly aligned with all releases. I'll try to automate this to tighten it up moving forward

**Comment by saimonmoore** [comment]
Awesome Carmine! Many thanks
