### ISSUE TITLE
Is discriminator supported?

### ISSUE THREAD

**Issue by nasht00** [cdimascio/express-openapi-validator#323]
Does it shortcut validation based on a specific field?

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#discriminatorObject

**Comment by cdimascio** [comment]
@nasht00, see my comment https://github.com/ajv-validator/ajv-keywords/issues/35#issuecomment-549176873

As AJV's author mentioned, from the validator's perspective, there is nothing to do. It's a no-op. 

However, when defaults are involved, there is some necessary work. The following [ticket](https://github.com/ajv-validator/ajv/issues/1119) has been created to handle defaults.

**Comment by cdimascio** [comment]
Two additional tickets to review
- https://github.com/cdimascio/express-openapi-validator/issues/95 (This describe it the no-op)
- Default value ambiguity in `oneOf` / Support for discriminator? https://github.com/cdimascio/express-openapi-validator/issues/104 (This is the defaults issue i noted above)

**Comment by cdimascio** [comment]
closing this as it's handled by issues #104 (open) and #95 (closed). 

if you feel your case is different, please reopen with more details, otherwise feel free to add more commentary to #104
