### ISSUE TITLE
Install the validator as standard express middleware i.e. via `app.use(...)` or `router.use(...)`

### ISSUE THREAD

**Issue by cdimascio** [cdimascio/express-openapi-validator#352]
**Is your feature request related to a problem? Please describe.**
I want to install the validator a standard connect middleware

**Describe the solution you'd like**
`app.use(OpenApiValidator.middleware(opts))`

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by cdimascio** [comment]
For those interested in v4, please provide feedback here or in this PR #351

**Comment by mahnunchik** [comment]
It seems `router.use` not supported for now https://github.com/cdimascio/express-openapi-validator/pull/351#issuecomment-684743497

**Comment by cdimascio** [comment]
@mahnunchik thanks made some progress on it in `v4.0.0-alpha.4`

**Comment by cdimascio** [comment]
available in v4!
