### ISSUE TITLE
schema references require a wrapping object

### ISSUE THREAD

**Issue by rogerzxu** [cdimascio/express-openapi-validator#356]
When using referencing schemas to define the request or response body, `express-openapi-validator` seems to require a wrapping object in order to pass request and response validation. 

### Given the following spec:
```
openapi: 3.0.2
servers:
  - url: http://localhost:9000/
info:
  description: Campaign API
  version: 0.0.1
  title: Campaign API
paths:
  /campaign:
    post:
      summary: Create campaign
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCampaign'
      responses:
        '201':
          description: Campaign successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CampaignResponse'
components:
  schemas:
    CampaignResponse:
      type: object
      required:
        - id
        - name
        - description
        - startDate
        - createdAt
        - updatedAt
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
        updateAt:
          type: string
          format: date-time
    CreateCampaign:
      type: object
      required:
        - name
        - description
        - startDate
      properties:
        name:
          type: string
        description:
          type: string
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time

```

#### Expected Behavior
I should be able to send a `POST` with body 
```
{
    "name": "test",
    "description": "description",
    "startDate": "2020-08-25T20:37:33.117Z",
    "endDate": "2020-08-25T20:37:33.117Z"
}
```

#### Actual behavior
The spec has a valid schema and does not error out when it is installed. In addition, my swagger docs also believe this to be perfectly valid:
![image](https://user-images.githubusercontent.com/1176771/91488542-70d84880-e87d-11ea-958e-2f6ec5a45c35.png)

However, sending the request results in the following error:
```
Bad Request: request should have required property 'body'
    at Object.POST-/campaign-application/json (.../node_modules/express-openapi-validator/dist/middlewares/openapi.request.validator.js:95:31)
    at RequestValidator.validate (.../node_modules/express-openapi-validator/dist/middlewares/openapi.request.validator.js:52:41)
    at requestValidationHandler (.../node_modules/express-openapi-validator/dist/index.js:162:79)
    at newFn (.../node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (.../node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (.../node_modules/express/lib/router/index.js:317:13)
    at .../node_modules/express/lib/router/index.js:284:7
    at Function.process_params (.../node_modules/express/lib/router/index.js:335:12)
    at next (.../node_modules/express/lib/router/index.js:275:10)
    at .../node_modules/express-openapi-validator/dist/middlewares/openapi.multipart.js:56:13
```

#### Workaround
After playing around, I was able to get satisfy the validator by changing up the spec like so:
```
schema:
  properties:
    campaign:
      $ref: '#/components/schemas/CreateCampaign'
```

But then my swagger docs believe that I need to wrap all the data like so:
![image](https://user-images.githubusercontent.com/1176771/91488845-ec39fa00-e87d-11ea-94c6-ecf4c1e6168d.png)

And based off of my reading from openapi docs, I believe the first example should be valid.

**Comment by cdimascio** [comment]
@rogerzxu the use case you describe is pretty straight forward and it should work.
i created the following [test case](https://github.com/cdimascio/express-openapi-validator/blob/master/test/issue.tests/356.campaign.spec.ts#L33) which uses your [spec](https://github.com/cdimascio/express-openapi-validator/blob/master/test/issue.tests/356.campaign.yaml). 
you'll see that the test, provides the expected request body. the test passes validation correctly. 

could it be that the IDL that your swagger ui refers to and IDL that your api uses are somehow different i.e. not using the same version.

im going to close this out as it doesn't appear to be a bug in the validation. 
if you can prove otherwise i'm happy to look into it

**Comment by rogerzxu** [comment]
Hi @cdimascio, the IDL used by swagger and the validator are definitely the same. 
I'm able to reproduce the bug in this sample project https://github.com/rogerzxu/express-openapi-validator-test

**Comment by cdimascio** [comment]
i see. looking at your example, i see that you do not have any body parser middleware. the validator expects that you will provide this.
 
have a look at the example [here](https://github.com/cdimascio/express-openapi-validator#example-express-api-server)

it should get you bootstrapped

**Comment by cdimascio** [comment]
@rogerzxu it looks like you did not register any bodyParser middleware. the validator expects that you will provide it.
have a look at the example [here](https://github.com/cdimascio/express-openapi-validator#example-express-api-server). it will get you bootstrapped

The key ingredient that you are missing is a body parser e.g
`const bodyParser = require('body-parser');` and `app.use(bodyParser.json());`

**Comment by cdimascio** [comment]
you will want to register that middleware https://github.com/rogerzxu/express-openapi-validator-test/blob/master/src/index.ts#L13

**Comment by cdimascio** [comment]
The README specifies this in the `Usage` instructions
https://github.com/cdimascio/express-openapi-validator#usage

> Note: Ensure express is configured with all relevant body parsers. Body parser middleware functions must be specified prior to any validated routes. See an example.

Let me know if you have thoughts on how to make this more apparent in the README
i'm sure others may have missed that step and run into similar issues

**Comment by cdimascio** [comment]
On another note, many other have also decided to use `'swagger-ui-express'` alongside `express-openapi-validator`

Would you mind fixing up your repo and perhaps renaming to something like `openapi-swagger-ui-example`?
If you decide to do so. Also, use either the async/await based `install` or the `v4.0.0-alpha.1` install which uses standard connect middleware.

You're repo, provides a a nice simple, example, of how to use `express-openapi-validator` with `swagger-express-ui`. Once cleaned up, I may consider referencing it from the swagger-ui FAQ question in the README.

**Comment by rogerzxu** [comment]
@cdimascio Thanks for your help! 

The bodyParser middleware was indeed the issue. In my case, I had it included in my original code, but had neglected to include it in the sample project. The reason it wasn't working in my original code was because I had it registered after the openapi spec was installed, but before the route definitions. The code [here](https://github.com/cdimascio/express-openapi-validator#example-express-api-server) states:
```
// 2. Set up body parsers for the request body types you expect
//    Must be specified prior to endpoints in 5.
```
which I think is inaccurate? I found that the validation wouldn't work correctly unless the bodyParser is registered before the openapi installation. 

I also updated my repo with the fix as well as some misc cleanup changes, please feel free to reference it.
