### ISSUE TITLE
v4.0.0-alpha.2 not published to NPM

### ISSUE THREAD

**Issue by mahnunchik** [cdimascio/express-openapi-validator#358]
**Describe the bug**

v4.0.0-alpha.2 not published to NPM https://github.com/cdimascio/express-openapi-validator/releases/tag/v4.0.0-alpha.2

**Comment by cdimascio** [comment]
alpha.2 is now out. 

@mahnunchik, have a look at and my https://github.com/cdimascio/express-openapi-validator/pull/351#issuecomment-687539345 to your question about the router and v4
