### ISSUE TITLE
Inferring wrong Content-Type in response validation

### ISSUE THREAD

**Issue by tannerntannern** [cdimascio/express-openapi-validator#360]
**Bug Description**
Response validation appears to infer the _request_ `Content-Type` rather than _response_ `Content-Type`, so even though I'm `res.json()`'ing my response, I get an error saying "Cannot validate content type multipart/form-data", since that's the content type of the request in my case.

**Context**
I'm using `4.0.0-alpha.1`

**My Hunch**
I took a peek at [openapi.response.validator.ts](https://github.com/cdimascio/express-openapi-validator/blob/v4/src/middlewares/openapi.response.validator.ts) and it looks like this may just be a typo.
* The warning I was seeing is from `console.warn('Cannot validate content type', contentType);` ([L165](https://github.com/cdimascio/express-openapi-validator/blob/v4/src/middlewares/openapi.response.validator.ts#L165))
* That `contentType` appears to be built from the result of `const contentTypeMeta = ContentType.from(req);` ([L48](https://github.com/cdimascio/express-openapi-validator/blob/v4/src/middlewares/openapi.response.validator.ts#L48))

Seems like this be `ContentType.from(res)` (instead of `req`) or similar?

**Comment by cdimascio** [comment]
@tannerntannern please give version `v3.16.13` or `v4.0.0-alpha.3` a try. both should provide improved inference on response types. note, these versions will utilize any `accept` header provided, if none provided it tries to discover a match

**Comment by cdimascio** [comment]
closing, please reopen if you still see issues

**Comment by tannerntannern** [comment]
Thanks for the quick work @cdimascio, `v4.0.0-alpha.3` seems to infer the response type correctly!
