### ISSUE TITLE
Zero and negative numbers aren't recognized as float

### ISSUE THREAD

**Issue by gsimon75** [cdimascio/express-openapi-validator#367]
**Describe the bug**
Zero and negative numbers aren't recognized as float, due to [this](https://github.com/cdimascio/express-openapi-validator/blob/7cb473bc9c085e10c8d77448385e7ddc737ceb38/src/framework/ajv/formats.ts#L23)

**To Reproduce**
Define a parameter for an operation to be type=number, format=float, minimum=-10, then try to call that operation with the param value of 0, 0.0, or -1.1

**Actual behavior** 
[{"path":".body.amount","message":"should match format \"float\"","errorCode":"format.openapi.validation"}]

**Expected behavior**
Accept zero and negative numbers as well.

**Examples and context**
An example or relevant context e.g. an OpenAPI snippet, an Express handler function snippet
```
requestBody:
  required: true
    content:
      application/json:
        schema:
          type: number
          format: float
          minimum: -10.0
```

**Comment by cdimascio** [comment]
@gsimon75 thanks for the issued. fixed in `v3.17.1`
