### ISSUE TITLE
Request validator middleware throws for valid requests (query parsing)

### ISSUE THREAD

**Issue by dystopiandev** [cdimascio/express-openapi-validator#369]
**Describe the bug**
I use [swagger-routes-express](https://www.npmjs.com/package/swagger-routes-express) to parse and mount OAS3 paths as express routes. I mount the routes after using:

```js
middleware({
  apiSpec: (validatedDefinition as unknown) as string,
  validateRequests: { allowUnknownQueryParameters: false },
  validateResponses: true,
  validateFormats: "full",
  $refParser: { mode: "dereference" },
  validateSecurity: true,
  operationHandlers: false
})
```
...but I get errors on all routes, whether or not they require any params.

**Actual behavior** 
Throws `Bad Request: request should have required property 'query'`

**Expected behavior**
Shouldn't throw, because all is right by the spec.

I solved it temporarily by changing:
```js
const valid = validator(Object.assign(Object.assign({}, req), { cookies }));
```
...to:
```js
const valid = validator(Object.assign(Object.assign({query: {}}, req), { cookies }));
```
...in `node_modules/express-openapi-validator/dist/middlewares/openapi.request.validator.js`

...so I reckon changing [this line](https://github.com/cdimascio/express-openapi-validator/blob/2f817f4fc61045d15a29243cb4622cc9e22efcf2/src/middlewares/openapi.request.validator.ts#L152) to
```ts
const valid = validator({ query: {}, ...req, cookies });
```
...should resolve this.

**Comment by cdimascio** [comment]
interesting. this almost seems as if some middleware in the stack is `null`ing out the req.query. typically, its `{}` when not present.

**Comment by dystopiandev** [comment]
> @dystopiandev interesting. this almost seems as if some middleware in the stack is `null`ing out the `req.query`. typically, its `{}` when not present. would you be willing to submit a PR with your proposed change? if so, check out [CONTRIBUTING.md](https://github.com/cdimascio/express-openapi-validator/blob/master/CONTRIBUTING.md) to get started

I'll send a PR shortly.

**Comment by dystopiandev** [comment]
@cdimascio #371
