### ISSUE TITLE
Can't resolve 'deasync' in '.../node_modules/express-openapi-validator/dist/framework'

### ISSUE THREAD

**Issue by Anxium** [cdimascio/express-openapi-validator#376]
**Describe the bug**

When I start my express server,  I got the following error:
```bash
ERROR in .../node_modules/express-openapi-validator/dist/framework/openapi.spec.loader.js
Module not found: Error: Can't resolve 'deasync' in '.../node_modules/express-openapi-validator/dist/framework'
```

My version of express-openapi-validator is *4.0.2*.

-- 

If I install the 'deasync' package locally, I don't get this error and everything work correctly.

I guess that 'deasync' must be a dependency of the package instead of a devDependency.

**Comment by cdimascio** [comment]
@Anxium thanks for the issue. This should be fixed in `v4.0.3`.
