### ISSUE TITLE
Performance issue with version 4.0.x

### ISSUE THREAD

**Issue by benblack86** [cdimascio/express-openapi-validator#384]
We just upgraded express-openapi-validator from 3.17.2 to 4.0.4 in our service and noticed at least a 20ms jump in latency.

I was wondering if anything comes to mind that could have caused the increase in latency and if you run any performance benchmarks. I can probably put an example together if that would help.

**Comment by rpastro** [comment]
We observed the same issue on our application after upgrading to v4, so we had to revert back to v3.17.1.

**Comment by cdimascio** [comment]
@benblack86 thanks will have a look. please, put together the example. it will help greatly. thx!

**Comment by cdimascio** [comment]
@benblack86 @rpastro @fluffywaffles please give `v4.0.7` a try. i believe the performance issue is now resolved

**Comment by benblack86** [comment]
@cdimascio yes, it is fixed. Thanks for the quick turn around, and the interface is looking a lot better!
