### ISSUE TITLE
Broken readOnly + required combination

### ISSUE THREAD

**Issue by karlismelderis** [cdimascio/express-openapi-validator#389]
**Describe the bug**
if prop is set to readOnly and required POST/PUT body validation is failing with "required item is missing"
(I'm at version 4.1.0)

**To Reproduce**
example schemas:
```yml
Item:
      allOf:
        - $ref: '#/components/schemas/id'
        - $ref: '#/components/schemas/name'

    id:
      properties:
        id:
          type: string
          readOnly: true
      required:
        - id

    name:
      properties:
        name:
          type: string
      required:
        - name
```

**Actual behavior** 
Error is thrown:
```json
{
  "errorCode": "required.openapi.validation",
  "message": "should have required property 'id'",
  "path": ".body.id"
}
```

**Expected behavior**
if prop is set to readOnly it's not checked in POST/PUT body

**Comment by cdimascio** [comment]
@karlismelderis I created [two tests](https://github.com/cdimascio/express-openapi-validator/blob/master/test/read.only.spec.ts#L212-L229) using the [schema](https://github.com/cdimascio/express-openapi-validator/blob/master/test/resources/read.only.yaml#L236-L253) provided above. both work correctly. It will be great if you can take at the [two tests](https://github.com/cdimascio/express-openapi-validator/blob/master/test/read.only.spec.ts#L212-L229) and modify them to reproduce the result you are seeing. Alternatively, if it's easier for you, please create simple canonical example demonstrating the issue, and post it to a github. i'll definitely have a look. thanks!

**Comment by karlismelderis** [comment]
ah missed comment. I will definitely try to create some code example for the case... or will find a bug in our schemas 🤔

**Comment by cdimascio** [comment]
Perhaps what u experienced is similar to https://github.com/cdimascio/express-openapi-validator/issues/400. If so, I am working on a fix

**Comment by cdimascio** [comment]
@karlismelderis a number of improvements were made for readonly/required support via pr #414. they are available in `v4.3.1` . please give it a try

**Comment by karlismelderis** [comment]
👍 that's exactly my case.
we are reusing schemas a lot so api spec is full with `allOf` e.t.c.
I managed to narrow down to exact same case:
```json
      "ItemDetails": {
        "allOf": [
          {
            "type": "object",
            "properties": {
              "createdBy": {
                "type": "object",
                "readOnly": true,
                "allOf": [
                  {
                    "type": "object",
                    "properties": {
                      "userId": {
                        "type": "string",
                        "description": "Unique user identifier, normally username"
                      },
                      "firstName": {
                        "type": "string",
                        "description": "Given Name"
                      },
                      "lastName": {
                        "type": "string",
                        "description": "Last (Family) Name"
                      }
                    }
                  }
                ]
              }
            },
            "required": [
              "createdBy"
            ]
          },
          {
            "properties": {
              "name": {
                "type": "string"
              }
            },
            "required": [
              "name"
            ]
          }
        ]
      }
```

**Comment by cdimascio** [comment]
@karlismelderis thanks for the example. 
does this occur in 4.3.x? 
also, you might try adding `type: object`  to the last object in the allOf list i.e.

```json
{
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    }
  },
  "required": [
    "name"
  ]
}
```

**Comment by karlismelderis** [comment]
👍 true. we missed some `type: object` in yml.

and issue is gone with latest version.
thank you for fixing it.
