### ISSUE TITLE
Unhandled schema messages in console with version 4.3.4

### ISSUE THREAD

**Issue by gonenduk** [cdimascio/express-openapi-validator#424]
**Describe the bug**
As of version 4.3.4 I get console.log messages like:
unhandled schema property: skipping { required: [ 'username', 'email' ] }
unhandled schema property: skipping { type: 'string', enum: [ 'user', 'moderator', 'admin' ] }
unhandled schema property: skipping { required: [ 'title' ] }
unhandled schema property: skipping { type: 'string' }

**To Reproduce**
Use the attached yaml file (attached in zip).

**Expected behaviour**
Not to print anything to the console.

**Examples and context**
[api.yaml.zip](https://github.com/cdimascio/express-openapi-validator/files/5443878/api.yaml.zip)

**Comment by gonenduk** [comment]
Update:
On 4.3.0 works ok.
On 4.3.1, 4.3.2 and 4.3.3 throws an exception (process exit).
On 4.3.4 we get the mentioned console logs.

**Comment by cdimascio** [comment]
@gonenduk good to hear from you again :) a fix is on the way

**Comment by cdimascio** [comment]
fixed in `v4.3.6`
