### ISSUE TITLE
path value starts with a dot

### ISSUE THREAD

**Issue by paulmarshall** [cdimascio/express-openapi-validator#43]
In some of your examples, the **path** attribute is prefixed with a dot, for example:

`
"path": ".params.id",
"path": ".query.limit",
`

This looks odd - is it a bug?

**Comment by cdimascio** [comment]
This message is provided by Ajv. We do minimal processing on that message.

We could attempt to process that message further or perhaps even add a hook to allow you to transform the value. However, this can already by achieved fairly easily without any new change.

For example

The following error handler will strip the first qualifier (if present), returning the message in your preferred format
e.g. 
```
  // Register error handler
  app.use((err, req, res, next) => {
    res.status(err.status || 500).json({
      errors: errors.map(p => ({...p, path: p.path.match(/^\.?(query|headers|path)?\.?(.*)/)[2]})
    });
  });
```
(Note, I'm sure there is a better regex that what I came up with above)

This custom error handler will transform the error message from e.g.

```
[ { path: '.query.limit',
    message: 'should have required property \'limit\'',
    errorCode: 'required.openapi.validation' },
  { path: '.query.test',
    message: 'should have required property \'test\'',
    errorCode: 'required.openapi.validation' } ]
> errors
[ { path: '.query.limit',
    message: 'should have required property \'limit\'',
    errorCode: 'required.openapi.validation' },
  { path: '.query.test',
    message: 'should have required property \'test\'',
    errorCode: 'required.openapi.validation' } ]
```

to (which i believe is your preference)

```
[ { path: 'limit',
    message: 'should have required property \'limit\'',
    errorCode: 'required.openapi.validation' },
  { path: 'test',
    message: 'should have required property \'test\'',
    errorCode: 'required.openapi.validation' } ]
```

Hope this helps

**Comment by cdimascio** [comment]
@paulmarshall please reopen if the proposed solution is not satisfactory. thanks!

**Comment by paulmarshall** [comment]
Good workaround - works for me, but puzzling why "Ajv" would think the dot prefix was acceptable in the first instance. Oh well - thanks for looking into this.
