### ISSUE TITLE
Json errors instead of html

### ISSUE THREAD

**Issue by th3g3ntl3men** [cdimascio/express-openapi-validator#434]
**Is your feature request related to a problem? Please describe.**
I think that errors should be uniform, if a error handler is passed an html error page should never show up. For example i pass a string as a json object to the api, and the middleware will spit a html error page back out. I feel like this should be a json object. 

**Describe the solution you'd like**
I think the library should return a json error if the handler is supplied. 

**Describe alternatives you've considered**
Re-writing the error

**Additional context**
This package is amazing. thanks for building.

**Comment by cdimascio** [comment]
@th3g3ntl3men can you provide more details or, better yet, an example.

As a quick test, I started [examples/1-standard](https://github.com/cdimascio/express-openapi-validator/tree/master/examples/1-standard), then `POST`ed a `string` instead of a `json object` to the `/v1/pets`, a json error is returned

POST request
```shell
curl  -XPOST localhost:3000/v1/pets -d 'test' -H 'X-api-key: asdfasfdsadf' -H 'content-type: application/json'
```
response
```json
{"message":"Unexpected token t in JSON at position 0"}
```

**Comment by th3g3ntl3men** [comment]
Ok so I think it was a collision of middleware. 

Basically I had. 

app.js

```js
const app = express();
 app.use(
      OpenApiValidator.middleware({
        apiSpec: path.join(__dirname, `../apis/${version}.yaml`),
        validateRequests: true, // (default)
        validateResponses: true, // false by default
      }),
      badMiddleware(), 
    );
```

The bad middleware was causing the error handler to not reformat to json. Sorry it took so long to track this down.
