### ISSUE TITLE
Dynamic query parameter case with GET request

### ISSUE THREAD

**Issue by sabbiu** [cdimascio/express-openapi-validator#445]
@cdimascio After running the curl request, it is now giving me an error message saying,

> Unknown query parameter

**Request**

```shell
curl http://localhost:3000/v1/pets\?type\=dog\&limit\=10\&test\=query
```

**Response**

```json
{
  "message":"Unknown query parameter 'test'",
  "errors": [
    {
      "path" : ".query.test",
      "message":"Unknown query parameter 'test'"
    }
  ]
}
```

Can you please verify this.

_Originally posted by @sabbiu in https://github.com/cdimascio/express-openapi-validator/issues/441#issuecomment-722786137_

**Comment by cdimascio** [comment]
i see. yes. this is a bit more involved than first thought. although, the initial issue is resolved, i need to dig deeper into additional props true with explode.

**Comment by cdimascio** [comment]
@sabbiu give `v4.4.2`a shot.

**Comment by sabbiu** [comment]
Thanks, It worked @cdimascio
