### ISSUE TITLE
My tests now fail with error: request should have required property 'headers'

### ISSUE THREAD

**Issue by davesag** [cdimascio/express-openapi-validator#447]
**Describe the bug**

In my [`api-server-boilerplate/pull/124`](https://github.com/davesag/api-server-boilerplate/pull/124) repo updating `express-open-api-validator` fails with error "request should have required property 'headers'".  I get the same error even if I set some headers in the request.

**To Reproduce**

- See this PR https://github.com/davesag/api-server-boilerplate/pull/124
- Or the CircleCI error https://app.circleci.com/pipelines/github/davesag/api-server-boilerplate/627/workflows/8acb5261-7a6d-48ca-b7fc-530baa664650/jobs/610

**Actual behavior** 

- In my server tests, using `supertest`, and even when setting `Accept: application/json` headers. the API validation fails saying "request should have required property 'headers'"

**Expected behavior**

I expect my tests to pass as before, as the API definition does not require any specific headers and these tests passed previously.

**Examples and context**

- See this PR https://github.com/davesag/api-server-boilerplate/pull/124
- Or the CircleCI error https://app.circleci.com/pipelines/github/davesag/api-server-boilerplate/627/workflows/8acb5261-7a6d-48ca-b7fc-530baa664650/jobs/610

**Comment by cdimascio** [comment]
this appears to e an issue with node 15. will look into it. for now you can use node 14

**Comment by cdimascio** [comment]
fixed in 4.4.3
