### ISSUE TITLE
No able to use response without content

### ISSUE THREAD

**Issue by vtajzich** [cdimascio/express-openapi-validator#455]
**Describe the bug**

When specific responses, like 204, needs to return no response, it fails on validator

**To Reproduce**
specify response with no content like
```responses:
        '204':
          description: no content
```

**Actual behavior** 
Fails on error ```no schema defined for status code '204' in the openapi spec```

**Expected behavior**
Skip response schema validation.
See `Empty Response` in https://swagger.io/docs/specification/2-0/describing-responses/

**Comment by cdimascio** [comment]
@vtajzich first off the spec you are referencing is swagger (openapi) 2. this project validates against the latest version, openapi 3. first, make sure that your spec conforms to openapi 3.x spec (this library does not support the older swagger 2 spec).

that said, no content responses should work. this [unit test](https://github.com/cdimascio/express-openapi-validator/blob/master/test/response.validation.spec.ts#L148) exists and passes.

**Comment by cdimascio** [comment]
@vtajzich closing this out. if you still feel there is an issue, please send along an example. based on existing tests, this seems to work

**Comment by emmagordon** [comment]
I'm also hitting this problem (using an openapi 3.0.0 spec) - ended up just turning response validation off altogether, which seems a shame.

**Comment by cdimascio** [comment]
Is this occurring with the latest version?

**Comment by cdimascio** [comment]
the test for this passes. also did a quick manual verify

server snippet:
```js
app.use(
  OpenApiValidator.middleware({
    apiSpec,
    validateResponses: true,
  }),
);
app.get('/v1/empty', function (req, res, next) {
  res.status(204).send();
});
```

openapi snippet
```yaml
paths:
  /empty:
    get:
      description: empty
      operationId: ping
      responses:
        '204':
          description: OK
```

invoke the api
```shell
curl -i localhost:3000/v1/empty

HTTP/1.1 204 No Content
X-Powered-By: Express
Date: Fri, 15 Jan 2021 00:58:13 GMT
Connection: keep-alive
Keep-Alive: timeout=5
```

it appears to work. if you are seeing different results, please provide an example and i'll have a look
