### ISSUE TITLE
Support for URI path params

### ISSUE THREAD

**Issue by CristianUser** [cdimascio/express-openapi-validator#457]
**Is your feature request related to a problem? **
I have an assets server and I use `/file/*` to take the rest as file location example `/file/folder/image.png`. following [RFC 6570](https://tools.ietf.org/html/rfc6570#section-3.2.3) I should be able to do it with `/file{/path*}` but it seems to be invalid here

**Describe the solution you'd like**
Add support to [Path segment templates](https://tools.ietf.org/html/rfc6570#section-3.2.6), if there's a way to do it currently please let me know

**Comment by cdimascio** [comment]
@CristianUser OpenAPI 3.x does not support RFC 6570, hence neither does the validator.
I happen to have the same use case. Currently, I use `ignorePaths` to ignore the route that requires this, then i validate it manually. That said, I'm experimenting with wildcards that are syntactically compatible with OpenAPI. We'll see where this goes. Ideally, the spec would support RFC 6570. If I come up with somethigng, I'd love to get your feedback.

**Comment by cdimascio** [comment]
@CristianUser have a look at https://github.com/cdimascio/express-openapi-validator/pull/491
Checkout the [README](https://github.com/cdimascio/express-openapi-validator/blob/8472092baa880c5877f5dc2a4d965d86455231ca/README.md#faq) update for this PR. It provides a description of the feature.

Unfortunately, it does not conform to RFC-6570. I'll certainly add support of OpenAPI supports it. In the meantime, the PR will satisfy a common case (which i believe is the case you are looking for)

Please share your thoughts

**Comment by CristianUser** [comment]
> @CristianUser have a look at #491
> Checkout the [README](https://github.com/cdimascio/express-openapi-validator/blob/8472092baa880c5877f5dc2a4d965d86455231ca/README.md#faq) update for this PR. It provides a description of the feature.
> 
> Unfortunately, it does not conform to RFC-6570. I'll certainly add support of OpenAPI supports it. In the meantime, the PR will satisfy a common case (which i believe is the case you are looking for)
> 
> Please share your thoughts

I like it, it should work for me 😅

**Comment by cdimascio** [comment]
@CristianUser this is available in `v.4.9.1`
