### ISSUE TITLE
How do you handle mongodb ObjectId ?

### ISSUE THREAD

**Issue by balazssoltesz** [cdimascio/express-openapi-validator#465]
Hello,

im trying to use express-openapi-validator with mongodb, but I can't figure out how should I handle ObjectId fields.
I have to specify id fields in the openapi.json as string, and in res.json() it will be converted to string as well, but if i set validateResponses to true then it will throw an error for me (id should be string).
Any idea how to handle properly mongodb _id fields?

**Comment by cdimascio** [comment]
You will want to send _id as a string. If you are returning the objectid as is, it's likely to be object and not a string, hence why the validator complains that it should be a string.

**Comment by balazssoltesz** [comment]
Yes I understand but practically it will be sent as string cause res.json() convert it to string. Should is iterate over the whole collection to convert any ObjectId field to string manually to avoid validator error?

**Comment by pilerou** [comment]
I managed objectid as described here
https://github.com/cdimascio/express-openapi-validator/issues/353

**Comment by pilerou** [comment]
@cdimascio it could be great to add it. If you want I could try to push for a merge request

**Comment by cdimascio** [comment]
hey all @pilerou has propsed a solution https://github.com/cdimascio/express-openapi-validator/pull/493
please have a look. feedback is greatly appreciated

**Comment by cdimascio** [comment]
@balazssoltesz this is now resolved by using the serDes option. See serDes doc. 

@pilerou has also provided a serializer/deserializer lib that can be used with the validator to handle mongodb object.

See the readme for details on both
