### ISSUE TITLE
Types for `apiSpec` option do not cover the entire spec

### ISSUE THREAD

**Issue by xeoneux** [cdimascio/express-openapi-validator#466]
**Describe the bug**
If I load a basic `petstore.json` with the `apiSpec` option in the middleware function in a TypeScript project and there will be an error thrown due to an incorrect type signature.

**To Reproduce**
Use https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.json with the `apiSpec` option in the middleware function in a TypeScript project

**Comment by cdimascio** [comment]
I created a new [test](https://github.com/cdimascio/express-openapi-validator/blob/master/test/petstore.spec.ts) for this using the petstore.json and I do not see an issue. 
The types check out on the full spec.
if you believe I've missed something, please have a look at the [test](https://github.com/cdimascio/express-openapi-validator/blob/master/test/petstore.spec.ts) to try to reproduce the issue you've observed. if you reproduce it, please file a PR with the test adjustments.
Thanks!
