### ISSUE TITLE
How to add an "Allow" header to the response when a 405 error occures?

### ISSUE THREAD

**Issue by electrotype** [cdimascio/express-openapi-validator#467]
On a "method not allowed" (`405`) error, I'd like to be able to add a [Allow ](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Allow)header to the response. This header would contain the valid methods.

For example, if a path only supports `GET` requests, and  a `POST` request is received, I'd like to be able to send a `Allow: GET` header.

Do you know how to achieve that?

**Comment by cdimascio** [comment]
The validator should probably do this automatically. I'd you want to take a stab at it, you can dig up where the 405 is returned in the response validator and add the allow header with the allowed http methods to the response.

**Comment by cdimascio** [comment]
available in `v4.12.5`
