### ISSUE TITLE
Response validation not working on status codes 400 and up

### ISSUE THREAD

**Issue by rosengrenen** [cdimascio/express-openapi-validator#469]
Hi, response validation does not seem to work on status codes 400+, and I tracked it down to `src/framework/modded.express.mung.ts:35`. I am wondering why this is the case, since it's not mentioned in the docs (I think) and had me confused for a bit. Is this a design choice or am I missing something here?

**Comment by cdimascio** [comment]
@rosengrenen could you provide your use case as well as the result you expect and the actual result.

**Comment by rosengrenen** [comment]
The use case would be attaching a json object with extra information about the error, along with the status code. For status codes 2xx (and 3xx) if the response does not match the schema an error is shown instead, but when doing the same with status codes 400+ the response is not checked, thus being able to send anything.

**Comment by vpalko** [comment]
Hi, 
I'm getting in same problem:
https://stackoverflow.com/questions/65244448/why-openapivalidator-may-not-validate-a-response

**Comment by robertparkinson** [comment]
I'm seeing the same thing. Writing tests and submitting a POST on a route that only has a GET. expected some sort of 4xx response but it is a 500 that is returned with error `POST method not allowed`

**Comment by cdimascio** [comment]
I’ll take a look and get this fixed. If u don’t mind, it will be great if someone can provide a canonical example spec and basic server that causes the error

**Comment by cdimascio** [comment]
Fixed in v4.10.6
