### ISSUE TITLE
Validation for properties fails completly

### ISSUE THREAD

**Issue by ahoehn** [cdimascio/express-openapi-validator#470]
**Bug**
- Additional unspecified properties do not result in an request validation error. 
- wrong property types do not result in an request validation error

**To Reproduce**
1. run 3-eov-operations example
2. send a POST request to http://localhost:3000/v1/pets with the following body
`{
    "name": 556,
    "type": "cat",
    "tags": [
        "purrfect"
    ],
    "test": "me"
}`

**Actual behavior**
- Response contains the name property which was a number instead of string as a string value
- not specified property "test" get's reflected
Example:
`{
    "id": 7,
    "name": "556",
    "type": "cat",
    "tags": [
        "purrfect"
    ],
    "test": "me"
}`

**Expected behavior**
A request validation error should send to the client for both validation errors

**Comment by cdimascio** [comment]
Can your provide the validator version?

**Comment by cdimascio** [comment]
@ahoehn this test passes and seems to reflect your use case

https://github.com/cdimascio/express-openapi-validator/blob/master/test/additional.props.spec.ts#L33-L49

Note it has both an additionalProperty (which fails validation) and a number passed as a string (which also fails validation)

Make sure you are using `additionalProperties: false` to deny additional props
The type cases should work

Going to close this out. If the problem persists, please reopen with a canonical failing example. If you can post the failing example on github somewhere. all the better.

thanks!
