### ISSUE TITLE
`NOT IMPLEMENTED` response for wrong endpoints

### ISSUE THREAD

**Issue by karlismelderis** [cdimascio/express-openapi-validator#472]
**Is your feature request related to a problem? Please describe.**
I might be missing something in config but I failed to figure how to change Not Found `404` response to Not Implemented `501` in case API path that's not part of API spec is called.

**Describe the solution you'd like**
either change default behavior or create/point to how to change response to `501`

**Describe alternatives you've considered**
Actually I'm not aware of any clean alternative.
API validation happens before express routes are evaluated.

**Comment by cdimascio** [comment]
@karlismelderis currently, there is no way to have the validator return a 501 rather than not found, thus the best option for this is to identify the 404 in your custom error handler middleware, then change the the response code manually.

e.g.

```java
app.use((err, req, res, next) => {
  // do stuff to identify the 404 error that you want to change to 501

  // return 501 and some error
  res.status(501).json({ 
    message: err.message,
    errors: err.errors,
  });
});

**Comment by cdimascio** [comment]
are you sure you want `501`? in most cases 404 is what you want.

https://tools.ietf.org/html/rfc7231#section-6.6.2
>>  The 501 (Not Implemented) status code indicates that the server does
   not support the functionality required to fulfill the request.  This
   is the appropriate response when the server does not recognize the
   request method and is not capable of supporting it **for any resource**.

https://tools.ietf.org/html/rfc7231#section-6.5.4
>> The 404 (Not Found) status code indicates that the origin server did
   not find a current representation for the target resource or is not
   willing to disclose that one exists.  A 404 status code does not
   indicate whether this lack of representation is temporary or
   permanent; the 410 (Gone) status code is preferred over 404 if the
   origin server knows, presumably through some configurable means, that
   the condition is likely to be permanent.
