### ISSUE TITLE
Using express-openapi-validator in production?

### ISSUE THREAD

**Issue by ErolPeel** [cdimascio/express-openapi-validator#475]
Hi!

Do you recommend using `express-openapi-validator` in production?
Is there a performance hit when `express-openapi-validator` is included, but request and response validation is disabled?

Greetings
Erol

**Comment by cdimascio** [comment]
@ErolPeel thanks for your interest in the validator

Yes. Many folks are running validator in production. 
I do not have specific performance data. 
Route schemas are compiled and cached and should be fast. 
My recommendation is to enable request validation in production and response validation in dev.
We work hard to ensure solid performance and do prioritize performance related issues. 
If you decide to do any perf testing, please provide your setup and results here. thanks

**Comment by ErolPeel** [comment]
> @ErolPeel thanks for your interest in the validator
> 
> Yes. Many folks are running validator in production.
> I do not have specific performance data. this will be valuable to collect.
> validation schemas are compiled and cached. they should be fast.
> 
> My recommendation is to enable request validation in production and response validation in dev.
> We work hard to ensure solid performance and do prioritize performance related issues.
> If you decide to do any perf testing, please provide your setup and results here. thanks
> 
> when disabling request validation, metadata (internal), security, and fileUpload middlewares are still enabled. you can disable fileUpload and security separately via options. that said, metadata middleware is always active.
> 
> all in all there are 5 registered middlewares
> 
> * fileUpload/multipart
> * request
> * response
> * security
> * metadata
> 
> all, but metadata can be disabled.
> if you want to disable it entirely, bypass using the middleware
> 
> note that from a security perspective, always validate API inputs. not doing so may expose significant risk

Thank you for your extensive answer.

**Comment by patricktyndall** [comment]
Hi @cdimascio, I'm looking into the overall latency overhead of using this project in prod, and wanted to follow up on production recommendations / performance tuning (are there docs anywhere on this topic)?

Usage info:
- I'm using v5.3.1 of the project
- Currently only want to use this project for request validation and no other features.
- We are using `dereference` refparser, which I imagine could have a performance impact.

I can identify anywhere from 4ms-250ms latency on a given request that can be attributed to EOV as a whole (I have 200+ endpoints) (though I'm not sure why that so widely varies. Data not scientific.)

Without knowledge of the internals, here are some things I've tried to get that number down:
- Disabling unused middleware seems a good place to start.
  - I am able to successfully remove multer middleware using `fileUploader: false`. 
  - However, when I set `validateSecurity: false`, I still see that a `securityMiddleware` is present on the output. Can you advise on the best way to remove any overhead associated with security? We do this ourselves. Do I need to pass a no-op function to avoid any work here?
- In addition to the 5 mentioned above, I also see a `pathParamsMiddleware`. Is this mandatory?
- I've also turned off `validateApiSpec: false`. I'm not sure how expensive or frequent this is, but we don't want to do this on every invocation.

Any other info on performance optimization for prod would be greatly appreciated (usage recommendations, scenarios where this library gets slow, etc). Love the work and want to make sure we use it sustainably. TIA!

**Comment by patricktyndall** [comment]
Sharing some traces from our deployed code (Running in lambda FYI). Wrapped the handlers in a timing function to get some data. I have also now upgraded to 5.3.8 (Lmk if I should update further, but I'm concerned that >5.4.0 will be a breaking change since we're using some OAS 3.1 concepts that may not work the same in 5.4.0). Times in milliseconds.

Note:
- These samples are *not* controlled for by endpoint, they appeared back to back in the same log group and I just grabbed them. I'm sharing to show the degree of variance, which is extreme.
- I also do not know the frequency of each scenario, though I see examples of each of this fairly often.

As you can see, the overall impact varies widely, as does the impact of each specific validator.
- Pic 1: pathParamsMiddleware *extremely* expensive. requestMiddleware also very expensive.
  - Note: This also is within a cold start / fresh container. Would we expect pathParams to be much slower on the first request after initialization?
- Pic 2: pathParamsMiddleware now 0ms. requestMiddleware still quite expeisnve.
- Pic 3: pathParamsMiddleware and requestMiddleware now extremely fast.

@cdimascio I would love to learn more about this so I can understand the latency issues affecting my app. I'm happy to dig further on specific scenarios or use cases that may be of interest / explain these differences. Any ideas/intuition/ gut feels on code paths / nondeterministically expensive work in the project that would account for these examples, and what key factors might explain the differences?

<img width="460" alt="image" src="https://github.com/user-attachments/assets/d79bdf99-4990-42cd-8225-bc6bba1c4af3" />

<img width="462" alt="image" src="https://github.com/user-attachments/assets/c3980534-d6e9-46c4-973b-396249e9eec6" />

<img width="469" alt="image" src="https://github.com/user-attachments/assets/8e1c0c4e-7f6b-452a-8f94-55e25ad09d7f" />

<img width="828" alt="image" src="https://github.com/user-attachments/assets/b05ba54e-5cfc-444e-aec5-e3662a1c457a" />

**Comment by cdimascio** [comment]
I see you've closed the issue. What were your findings

**Comment by patricktyndall** [comment]
Not my issue, this was already closed. I can make another if better

**Comment by cdimascio** [comment]
When initializing the validator middleware, it loads and pre-processes the openapi schema file. This process occurs once. The result of this step is cached in memory and reused for all validations. 

This one time process is asynchronous, hence api requests submitted during the step are accepted, but must wait for step to complete. 

Each cold start will trigger this given a new express instance is started.

Some potential ways to mitigate the startup cost are to keep the lambda warm, ultimately avoiding the cold start. Also, other types compute like ECS, etc, can provide a bit more control over when an instance is deemed ready to accept traffic. For instance, it could be deemed ready once the middleware has completed its one time load/preprocess step (This can be determined by looking for req.openapi--perhaps via a health check). There are certainly other options as well.

Note: full spec validation can be bypassed as you noted. It is run only once, at startup, during the load preprocess step.

**Comment by patricktyndall** [comment]
Thanks. Unfortunately leaving lambda or keepaliving/avoiding the serverless paradigm is not an option, but I understand it imposes constraints.

Is it safe to say this library is not intended for serverless use? Would be good to know these costs upfront ideally, but I understand that's a minor detail in a project like this.

Yeah this makes sense:
- I see in [the code here](https://github.com/cdimascio/express-openapi-validator/blob/97158fd070620e328c9d43fcdb3fb5c01010946c/src/openapi.validator.ts#L133) that the pathParamsMiddleware does this setup once, skipping on subsequent invocations if `inited`.
- I see something similar [here](https://github.com/cdimascio/express-openapi-validator/blob/97158fd070620e328c9d43fcdb3fb5c01010946c/src/openapi.validator.ts#L193) for the requestMiddleware - reusing the `reqmw` if present.

A couple of questions / notes though:
- Why is this done in the first request, vs. on library initialization? Doing it on init would allow us to more closely monitor this as part of cold start duration (other libs e.g. sequelize do all the expensive work at require phase).
- `validateApiSpec: false` does not make anything any faster. It might save a few ms (don't have concrete data), but the times reported above are with that option already set to false. No noticeable change there.

Most importantly, this does NOT explain the variations in the `requestMiddleware` latency. Even on non-cold starts, I still see lots of 300ms delays on the requestMiddleware, and on others it is 0. This leads me to believe there is some other factor here besides the cold start aspect.

Any thoughts on any of this? Would love to get some time back if possible, or at least understand the exact tradeoffs better. Thanks in advance, appreciate the work.

**Comment by cdimascio** [comment]
The validator is not opinionated with respect to compute. Lambda is a perfectly reasonable use. 

Regarding the observed latencies, I suspect there is something more at play. On the surface, the numbers are far too high to be attributed to validation. 

I suggest hooking up a profiler to better understand the issue. Node's profiler or something like clinicjs can help pinpoint the issue.

**Comment by patricktyndall** [comment]
Ok thanks.

Re: Initialization: That would be great. As is, even provisioning concurrency will not solve this issue, as we'd still see a latency spike on the first request, even if the container has been warm.

Re: req validation being too long:
- I'm glad to hear that you think it's too long (is this still your gut feel even for a large API with `dereference` and ~300 endpoints?).
-  Can you say more about that suspicion (before I start trying to reverse engineer this library)? Or are you saying you think it's something else in my code?
- I did investigate / eliminated other culprits before escalating here, so I'm pretty sure it's something running in that middleware.

**Comment by patricktyndall** [comment]
Hi @cdimascio if I could trouble you for one more reply here to my above questions - I have no idea where to start (what patterns should I look for, what configs to use, what are the main contributors / possible culprits for high CPU usage, etc). Even if it's just a gut feel, some direction would be helpful.

Thanks in advance. Very happy to provide other information / try things.

I really want this library to be viable long-term for a project with a large and detailed API spec and am eager to eliminate this latency.

**Comment by cdimascio** [comment]
You might start with clinicjs, then generate some load with autocannon and produce a flamegraph. This may be a reasonable starting point. The clinicjs doc can get you started

**Comment by patricktyndall** [comment]
thanks. more meant in terms of areas of the codebase. i'll update here when I get around to that
