### ISSUE TITLE
Documentation for using express-openapi-validator with NestJS

### ISSUE THREAD

**Issue by ghost** [cdimascio/express-openapi-validator#476]
I am new to NodeJS and TypeScript and I am writing a service with [NestJS](https://nestjs.com/).

Is there an example for how to register express-openapi-validator as a [NestJS middleware](https://docs.nestjs.com/middleware)?

**Comment by bernhardvollnhofer** [comment]
I was able to register the validator with NestJS now:

```typescript
configure(consumer: MiddlewareConsumer) {
    middleware({
        apiSpec: `${__dirname}/../api-doc/bff-api.yaml`
    }).forEach(value => consumer.apply(value).forRoutes(OrganizationController))
}
```

**Comment by ErolPeel** [comment]
I was able to register the validator with NestJS now:

```typescript
configure(consumer: MiddlewareConsumer) {
    middleware({
        apiSpec: `${__dirname}/../api-doc/bff-api.yaml`
    }).forEach(value => consumer.apply(value).forRoutes(OrganizationController))
}
```

I hope, this is correct.

**Comment by adriengibrat** [comment]
Very interesting, could you provide a more detailed snippet or a link to an example repository.
I'd really like to have a API spec first approach for NestJS (instead of the current Swagger generation).

thanks ;)

**Comment by cdimascio** [comment]
@adriengibrat, there is an [SO](https://stackoverflow.com/questions/65092351/how-to-install-express-middleware-express-openapi-validator-in-nestjs) that describes an approach similar to @ghost's.

 if it works out, please submit a PR with steps to integrate. it will be great to add them to the readme.

@ghost, it sounds like you've had some success. could you post a working example to a github repo and link it here? it will be great to have working code that folks can experiment with

**Comment by ahilke** [comment]
@cdimascio I created a demo project here: https://github.com/ahilke/nestjs-with-express-openapi-validator/tree/express-openapi-validator-476

Hope it helps!

**Comment by cdimascio** [comment]
Thanks @ahilke! Feel free to create a PR that's adds this code to the examples folder in this project.

**Comment by ahilke** [comment]
Problem is, I haven't found a good solution for the [exception filter](https://github.com/ahilke/nestjs-with-express-openapi-validator/blob/express-openapi-validator-476/src/openapi-exception.filter.ts) yet:

```ts
import { ArgumentsHost, Catch, ExceptionFilter } from "@nestjs/common";
import { Response } from "express";

// FixMe: Use error types from index file
import { HttpError } from "express-openapi-validator/dist/framework/types";

@Catch(HttpError)
export class OpenApiExceptionFilter implements ExceptionFilter {
    catch(error: HttpError, host: ArgumentsHost) {
        const ctx = host.switchToHttp();
        const response = ctx.getResponse<Response>();

        response.status(error.status).json(error);
    }
}
```

I haven't found a solution yet that only uses the exports from the index file. The filter is needed as otherwise NestJS would convert all validator errors to 500 errors.
I think I could use the error classes from `error` in the `@Catch()` decorator, but I cannot use them to type the `error` object in `catch()`.

**Comment by lucashanke** [comment]
Hey @ahilke 

I could leverage that solution:

```
import { ArgumentsHost, Catch, ExceptionFilter } from '@nestjs/common';
import { Response } from 'express';

import { error } from 'express-openapi-validator';

@Catch(...Object.values(error))
export class OpenApiExceptionFilter implements ExceptionFilter {
  catch(error, host: ArgumentsHost) {
    const ctx = host.switchToHttp();
    const response = ctx.getResponse<Response>();

    response.status(error.status).json(error);
  }
}

```

**Comment by ahilke** [comment]
Thank you @lucashanke, I did not think about using `Object.values` in this way. 

I opened a MR here: https://github.com/cdimascio/express-openapi-validator/pull/554

I don't like that `error` in this case is implicitly typed as `any`, so I added an interface based on `HttpError`. Not sure whether that's a good idea, but at least it makes the assumptions about the error structure explicit.
