### ISSUE TITLE
Errors for unknown format

### ISSUE THREAD

**Issue by robianmcd** [cdimascio/express-openapi-validator#48]
An error is thrown when there is a custom format on a property. e.g. if the api spec has something like:
```YAML
properties:
  phoneNumber:
    type: string
    example: +15017122661
    format: phone-number
```

This will result in an error like

`Error: unknown format "phone-number" is used in schema at path "#/properties/body/properties/phoneNumber"`

The OpenAPI spec is pretty flexible on formats so I think this should be allowed. E.g. this page says (https://swagger.io/specification/):

> Primitives have an optional modifier property: format. OAS uses several known formats to define in fine detail the data type being used. However, to support documentation needs, the format property is an open string-valued property, and can have any value. Formats such as "email", "uuid", and so on, MAY be used even though undefined by this specification. Types that are not accompanied by a format property follow the type definition in the JSON Schema. Tools that do not recognize a specific format MAY default back to the type alone, as if the format is not specified.

**Comment by cdimascio** [comment]
Agreed. This should be looked at.

**Comment by cdimascio** [comment]
i've made progress on this issue. A fix should be available by the end of the week

**Comment by cdimascio** [comment]
@robianmcd @richdouglasevans @SilkJaer Unknown formats are supported in v2.4.0. Please give it a spin. I welcome any feedback

**Comment by robianmcd** [comment]
Great to hear. Thanks!
