### ISSUE TITLE
Inconsistent validation of multipart body defined with $ref 

### ISSUE THREAD

**Issue by setaman** [cdimascio/express-openapi-validator#495]
Hello, I am trying to validate a `multipart/form-data` request body. The following spec is given:
```yml
...
requestBody:
        $ref: "#/components/requestBodies/Image"
...

components:
  requestBodies:
    Image:
      required: true
      content:
        multipart/form-data:
          schema:
            type: object
            required:
              - image
            properties:
              image:
                type: string
                format: binary
          encoding:
            image:
              contentType: image/png, image/jpeg
```
As you can see, I point to the body definition with `$ref`. When a request is made to the endpoint, the validator reports an error and says that the required `image` field is not present. The spec is valid, I have also validated it with other tools.

I spent several hours trying to figure out what the reason could be. Then I removed `$ref` and wrote down the body definition directly in the route. And voila, it works like expected!

Please note that `$ref` works wonderful with `application/json` body. This problem appears in my case only with multipart. 
During my research I also saw that you had commented out `$ref` [in this example](https://github.com/cdimascio/express-openapi-validator-example/blob/90975ab0c0f3db9dce5d9ea86bdef4dc0c03aa28/openapi.yaml#L154) as well. So, any thoughts on this?

**Comment by cdimascio** [comment]
@setaman this is a bug. the use of `requestBodies` is causing the problem. For now, you could extract the schema object out e.g

```yaml
/sample_4:
  post:
    description: upload an image
    requestBody:
      content:
        multipart/form-data:
          schema:
            $ref: '#/components/schemas/Image'
    responses:
      200:
        description: upload success
```

```yaml
components:
  schemas: 
    Image:
      type: object
      required:
        - image
      properties:
        image:
          description: the image
          type: string
          format: binary
```

**Comment by cdimascio** [comment]
@setaman fixed in `v4.9.5`

**Comment by setaman** [comment]
@cdimascio thanks, awesome, life saver on the last working day before holiday. But what happened to the README? Documentation disappeared.

**Comment by cdimascio** [comment]
@setaman np. thanks letting me know about the README. its back
