### ISSUE TITLE
Add method to force initialization without waiting for first request

### ISSUE THREAD

**Issue by arsnyder16** [cdimascio/express-openapi-validator#514]
**Is your feature request related to a problem? Please describe.**
I am seeing some delays on my first request as the middleware is processing my yaml and attaching the operation handlers 

**Describe the solution you'd like**
It would be nice to have a way to initialize this process so i can do that before the first request happens

**Comment by arsnyder16** [comment]
I would presume there are some performance improvements that could possibly be made as well. For context i have about 52 endpoints currently and 7 files that contain the operations. I am using `operationId` and `x-eov-operation-handler`

**Comment by cdimascio** [comment]
@arsnyder16, would you mind installing from the cmd/preprocess/visit-optimize branch
```bash
npm install 'cdimascio/express-openapi-validator#cmd/preprocess/visit-optimize' --save
```
this is likely not to make a huge difference, but given the size of your api perhaps it will provide some savings. give it a shot, let me know the result

**Comment by arsnyder16** [comment]
@cdimascio Installing with that command causes the module to not work, i haven't installed this way before so maybe i am missing something on how this should work 

![image](https://user-images.githubusercontent.com/6554919/104103040-09d89080-526e-11eb-961f-641a017c03c9.png)

**Comment by cdimascio** [comment]
@arsnyder16 , try this instead `npm install express-openapi-validator@4.11.0-beta.1`

**Comment by cdimascio** [comment]
@arsnyder16 these improvement are now included in `v4.10.5`. please let me know if you see any improvement in startup time

**Comment by arsnyder16** [comment]
@cdimascio This made a huge difference, the load time now is insignificant

**Comment by cdimascio** [comment]
Awesome! Great news!
