### ISSUE TITLE
do not validate request if path does not exist in openapi spec

### ISSUE THREAD

**Issue by plastic-abubakr** [cdimascio/express-openapi-validator#52]
I am serving frontend and restful APIs within a same app. I want to validate only my restful APIs which have a openapi spec, however, my frontend pages are throwing not found errors because these paths do not exist in the specification.

Is there a way to limit validation to a certain path, for example, /api/? Or even disable not found errors for paths not found in openapi spec?

**Comment by cdimascio** [comment]
@plastic-abubakr it is intended to validate anything under the root path (as defined in the openapi spec). Paths not under the root should be ignored by the validator. Is this not happening?

**Comment by cdimascio** [comment]
@plastic-abubakr, this test verifies that this 'should' work. i also test manually to be sure
https://github.com/cdimascio/express-openapi-validator/blob/master/test/routes.spec.ts#L198

Please let me know if you still believe this is an issue. If so, perhaps you can send me a few snippets to help reproduce. 

thanks so much for your interest in this project!

**Comment by richdouglasevans** [comment]
Just dropping by to say that I had to figure this out by looking at the tests: it wasn't obvious to me.

Is it worth me submitting a PR to add a FAQ or something like that to document this?

**Comment by cdimascio** [comment]
@richdouglasevans please do. thanks so much!
