### ISSUE TITLE
Broken link to unit test examples in README.md 

### ISSUE THREAD

**Issue by jontroncoso** [cdimascio/express-openapi-validator#523]
**Describe the bug**
The readme has `See OpenAPI 3 authentication for securityScheme and security documentation See examples from unit tests`. but the link is broken (links to https://github.com/cdimascio/express-openapi-validator/blob/security/test/security.spec.ts#L17)

**To Reproduce**
1. Click `examples` link in README. 
2. Get 404.

**Actual behavior** 
I get a 404.

**Expected behavior**
See examples of unit test when i click that link.

**Examples and context**
<img width="1085" alt="Screen Shot 2021-01-21 at 5 01 44 PM" src="https://user-images.githubusercontent.com/300521/105417945-5a56d300-5c0a-11eb-8742-6d53896b3048.png">

**Comment by cdimascio** [comment]
@jontroncoso thanks you for the issue. the link isnow fixed.
