### ISSUE TITLE
Required + nullable seems to not work

### ISSUE THREAD

**Issue by RoXuS** [cdimascio/express-openapi-validator#526]
We have an issue if we use required AND nullable true on a property.

Our spec
```
		"OrganizationDto": {
			"type": "object",
			"required": ["fax"],
			"properties": {
			         ...
				"enabled": {
					"type": "boolean"
				},
				"fax": {
					"type": "string",
					"nullable": true
				},
                          ...
```
it produces 
```
export interface OrganizationDto {
  enabled?: boolean;
  fax?: string | null;
````
instead of
```
export interface OrganizationDto {
  enabled?: boolean;
  fax: string | null;				
```

For us, undefined should be != than null.

If nullable is not set the property is ok `fax: string`.
If required is not set the property is ok too `fax?: string | null`

**Comment by cdimascio** [comment]
What are you using to producing those interfaces? 

It is that tool, not express-ooenapi-validator, that has the issue.

**Comment by RoXuS** [comment]
we use springdoc. But maybe I didn't understand the spec. Why you say this is an issue on our tool?

**Comment by RoXuS** [comment]
Ok I understand, sorry ^^

**Comment by cdimascio** [comment]
No problem. OpenAPI deviates a bit from jsonschema. Nullability is one of those areas. These edges are often the more problematic / inconsistent.
