### ISSUE TITLE
You Can Haz Coffee?

### ISSUE THREAD

**Issue by richdouglasevans** [cdimascio/express-openapi-validator#53]
Carmine, I went to buy you some coffees… but I was denied 😭 

<img width="458" alt="coffee" src="https://user-images.githubusercontent.com/1855109/65375436-8d432c80-dc8d-11e9-8461-11cd9318d14f.png">

Carmine, this **mission critical** issue needs your **urgent** attention ❌ ☕️➡️ ☕️ ✅

**Comment by richdouglasevans** [comment]
Hurrah! This has been resolved and the coffee is now flowing like a fine wine ☕️ 🎉

**Comment by cdimascio** [comment]
Thank you!
