### ISSUE TITLE
Q: How can I validate an API Documentation with an API server URL?

### ISSUE THREAD

**Issue by moatazeldebsy** [cdimascio/express-openapi-validator#532]
Q: How can I validate an API Documentation with a live API server URL?

**Comment by cdimascio** [comment]
Hello @moatazeldebsy, could you provide more context. I don't completely understand the question.

**Comment by moatazeldebsy** [comment]
Hello, @cdimascio thank you for your replay, actually, I'm can I validate that the implementation of the API is sync with the API documentation such as openapi 3.x yaml files, I have a yaml file and I want to validate that the documentation is what implemented to make sure that the live API URL is updated, is it clear now?

**Comment by cdimascio** [comment]
@moatazeldebsy thanks for the clarification
The validator takes a design first approach. You write your spec, then implement your business logic
By default request validation is turned on i.e. `validateRequests: true`. This ensure requests to your service are valid against your specification. You may also enable `validateResponses: true`.  This will ensur outgoing responses from you service match your spec.
