### ISSUE TITLE
Custum error message for custom formats

### ISSUE THREAD

**Issue by pietervandereems** [cdimascio/express-openapi-validator#540]
The api I'm currently developing is pretty extensive and the openapi specification is also pretty extensive. To keep it all manageable the specification is spread out over many yaml files (using $ref) and generous use of allOf to combine specs.
When I then use a custom format and it triggers, the error created becomes unreadable.

Example:
### openapi files:
**station.yaml**
```
station_post:
  type: object
  properties:
    x_coordinaat:
      type: rdxcoordinate
    y_coordinaat:
      type: rdycoordinate
```

**station_uri.yaml**
```
station_uri:
  put:
    operationId: station_uri_put
    requestBody:
      content:
        application/json:
          schema:
            allOf:
              - $ref: "./station.yaml#/station_base"
              - $ref: "./station.yaml#/station_post"

```
**openapi.yaml**
```
openapi: 3.0.3
paths:
  "/station":
    $ref: "./station_uri.yaml#/station_uri"

```
### Error thrown:
"schema is invalid: data.properties['body'].properties['x_coordinaat'].type should be equal to one of the allowed values, data.properties['body'].properties['x_coordinaat'].type should be array, data.properties['body'].properties['x_coordinaat'].type should match some schema in anyOf, data.properties['body'].properties['y_coordinaat'].type should be equal to one of the allowed values, data.properties['body'].properties['y_coordinaat'].type should be array, data.properties['body'].properties['y_coordinaat'].type should match some schema in anyOf",

###What I would like it to be is:
"x_coordinaat is not withing range, y_coordinaat is not within range."

What I'm thinking of is a added option for an error message. Like:
```
  formats: [
    {
      name: 'rdycoordinate',
      type: 'number',
      validate: (v) => (v >= 1 && v <= 100),
      error: 'is not within range'
    },
    {
      name: 'rdxcoordinate',
      type: 'number',
      validate: (v) => (v >= 30 && v <= 40),
      error: 'is not within range'
    }
  ],
```

**Comment by cdimascio** [comment]
Custom formats apply to values of the `format` keyword, not `type`. See [here](https://swagger.io/docs/specification/data-models/data-types/#string-format) for details on format

**Comment by cdimascio** [comment]
Closing out. Type just be a valid type e.g. string. A custom format can be used alongside a valid type

**Comment by cdimascio** [comment]
Let me know how things go once u sort out the format issue
