### ISSUE TITLE
Array.prototype['flatMap']

### ISSUE THREAD

**Issue by aaronluman** [cdimascio/express-openapi-validator#547]
**Describe the bug**
adding the [flatMap method to Array](https://github.com/cdimascio/express-openapi-validator/blob/b802dd1eb6643f7867b69142705eb35be3854856/src/middlewares/parsers/schema.preprocessor.ts#L56) objects is a global event (it effects the project importing express-openapi-validator and all of their dependencies). the flatMap method as currently added acts as a hidden element of the array.

**To Reproduce**
Call 
```
for (let i in *any array*) {
}
```
the last value of i will be "flatMap"

**Actual behavior** 
The result of this is that any dependency that loops arrays using for (i in array) and then attempts to access the elements by position will throw an error (array["flatMap"] does not exist)

Marking the property as not enumerable resolves the issue

**Comment by cdimascio** [comment]
thanks @aaronluman, fixed in `v4.12.1`
