### ISSUE TITLE
Validation for security

### ISSUE THREAD

**Issue by gonenduk** [cdimascio/express-openapi-validator#55]
Validate if the security defined in the api spec exists in the api call.
If doesn't exist should return 401.

**Comment by cdimascio** [comment]
This is a feature we should add

**Comment by cdimascio** [comment]
I've started work on security validation, https://github.com/cdimascio/express-openapi-validator/tree/security
It should be coming relatively soon

**Comment by gonenduk** [comment]
I think the best would be if you only verify the existence of the required security object and not verify the security itself because it is related to implementation.
For example, suppose we require a JWT in the header. You should only check if the authentication header value exists and if not return 401. You should not verify the token itself. This will be done in the routes of the app that is using your lib. If the token is invalid it will return also 401. If the user has not enough permissions it will return 403 or 404 and so on...
The plus is it is easy to implement. The minus is that security validations (not if the token exists but if it's valid and so on) will be done after the other validations you do for the parameters.
What do you think?

**Comment by cdimascio** [comment]
I agree. Your description is very much in line with my thinking. The first version will provide hooks to allow the developer to provide the actual security validation logic. As you mentioned, in the case of a missing auth header the validator can certainly return the 401 directly. Anything more complicated will be left to the developer. At the start, the developer will be required to handle much of the auth logic via the hooks. If there are additional concerns that the validator can offload from the user, I’ll certainly consider them. Like anything, we’ll continue to evolve and improve

**Comment by gonenduk** [comment]
I think you can actually release the first version even without hooks. Only verify the required security entity exists and return 401 if it doesn't.
Hooks are useful only to perform the security validation in full before you continue to validate the other parameters.

**Comment by cdimascio** [comment]
That’s a good point. Very much appreciate your thoughts and perspective.

**Comment by cdimascio** [comment]
v2.5.0 now provides security validation.
please give it a try. 
i'm super interested to hear you feedback.
thanks!

**Comment by gonenduk** [comment]
Hi,
Thanks for the effort!
I am still trying to understand how to use the hooks and why I need them instead of doing the checks done in the hook in the normal handlers. Maybe it's good for seperation.

Anyway, I tried to call an api that requires a JWT in the header without having one set. I got this error: "message": "Cannot read property 'JWT' of undefined"
Is this your error or the package that tries to read the property?

**Comment by cdimascio** [comment]
Thanks for he feedback. I will think on providing the info to downstream middleware as well. The data would need to be hung on the request to do it. Hooks provide the data explicitly through a function call. If you have example of a lib that does things differently or perhaps more intuitively, please let me know.I’ll certainly have a look and potentially incorporate ideas here.

 As for the JWT error, that is  likely the package that’s trying to read the JWT. The validator does not do anything specific with JWTs.

Also it may be useful for debugging,  to output a stack track in your error handleR to get more information about where the failure occurred.

**Comment by cdimascio** [comment]
I’ll also look to provide a more complete example with auth, so that it’s easier to get up and running quickly

**Comment by gonenduk** [comment]
The fact that the error states JWT it means it comes from the validator.
The actual code only checks the token and gets it from the authentication header.
Anyway, this is the stack of the error 401:
error [rid: 4f71c374-25a9-4ca2-b8f6-9731460ddaf6]: Error: Cannot read property 'JWT' of undefined
    at Object.validationError (/Users/gonen/repos/basejs/node_modules/express-openapi-validator/dist/middlewares/util.js:23:25)
    at Object.<anonymous> (/Users/gonen/repos/basejs/node_modules/express-openapi-validator/dist/middlewares/openapi.security.js:48:32)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/gonen/repos/basejs/node_modules/express-openapi-validator/dist/middlewares/openapi.security.js:4:58)
    at tryCatcher (/Users/gonen/repos/basejs/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/gonen/repos/basejs/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/gonen/repos/basejs/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (/Users/gonen/repos/basejs/node_modules/bluebird/js/release/promise.js:641:10)
    at _drainQueueStep (/Users/gonen/repos/basejs/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/Users/gonen/repos/basejs/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/gonen/repos/basejs/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/gonen/repos/basejs/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)

Can I have your messenger, email to anything so we can communicate more easily?

**Comment by cdimascio** [comment]
Sure thing. I just set up a gitter. Let's see if this helps. Join the chat: https://gitter.im/cdimascio-oss/community
I'll be back online in a few hours

**Comment by cdimascio** [comment]
@richdouglasevans @sheldhur @SpencerLawrenceBrown you may be interested in the gitter community. 
feel free to chime in. we've had a small discussion around the openapi security feature. 
i recently delivered a version of the feature, however, i'm very much open to feedback. i want to make sure that what is implemented in done in a useful way. @gonenduk has already had some good feedback. would love to get your thoughts as well
