### ISSUE TITLE
Unknown format "decimal" is used in schema

### ISSUE THREAD

**Issue by MostafaAbdlrazek** [cdimascio/express-openapi-validator#56]
Whenever I try to validate a request against an openapi.yaml file that contains a `type: number` with `format: decimal` I receive the following error:
```
{
    "errors": [
        {
            "message": "unknown format \"decimal\" is used in schema at path \"#/properties/amount\""
        }
    ]
}
```

**Comment by richdouglasevans** [comment]
This _may_ be related to #48 

`decimal` isn't in t[he list of formats defined by the OAS](https://spec.openapis.org/oas/v3.0.0.html#data-types) so I _guess_ that's why the OpenAPI validator is erroring. (I think this is a legit bug 'cos it shouldn't.)

> However, to support documentation needs, the format property is an open string-valued property, and can have any value. Formats such as "email", "uuid", and so on, MAY be used even though undefined by this specification.

**Comment by cdimascio** [comment]
Thanks @richdouglasevans. Will look into providing a sane default. 
@MostafaAbdlrazek if possible you can work around this by using one of the defined number types / formats

**Comment by cdimascio** [comment]
unknown formats are supported in v2.4.0.

**Comment by gonenduk** [comment]
I think this issue can be closed.
