### ISSUE TITLE
response validator errors out on validation of strings

### ISSUE THREAD

**Issue by rohshall** [cdimascio/express-openapi-validator#566]
In my OpenApi specs, I have timestamp fields, which are defined as of type "string". However, the response validator flags it saying this field is not a string. When I define it as of type "object", the validation passes. But, it is incorrect. As per the OpenApi spces, date-like fields should be defined as "string", with additional "format" as "date" or "date-time".
In the API, request validation of timestamps work correctly. It is only a problem for response validation.
I am using the latest version "4.12.6" (had the same problem with "4.12.5")

**Comment by cdimascio** [comment]
@rohshall, thanks for the issue.

Can u provide a canonical example demonstrating the issue. 

Based on he description, it sounds like you've defined a schema on a response object that uses a date format
E.g

```yaml
type: string
format: date-time
```

In this case, there are wo serializers (date and date-time) that are installed by default. Each will handle a date string or a `Date` object. If a Date object is found, it should serialize it according to the date format. If a string is found it should validate it's format. 

Noting this in case it helps identify the issue.

FYI @pilerou

**Comment by rohshall** [comment]
I tried it with a sample application: https://github.com/cdimascio/express-openapi-validator-example, and it works as expected. Sorry, something must be wrong in my app. We can close this issue.
