### ISSUE TITLE
OpenAPI 3.1 support

### ISSUE THREAD

**Issue by thernstig** [cdimascio/express-openapi-validator#573]
**Is your feature request related to a problem? Please describe.**
OpenAPI 3.1 was released a while ago. It would be nice if it was supported.

**Describe the solution you'd like**
Full OpenAPI 3.1 support.

**Additional context**
https://openapi.tools/ lists this tool as not having OpenAPI 3.1 support.

**Comment by essential-randomness** [comment]
I tried my hand at this and failed. See: https://github.com/cdimascio/express-openapi-validator/pull/653

I don't think this is possible right now, but I'm waiting for help from the AJV folks to see if they can help figure out what I'm doing wrong (or whether there is an error in any of the libraries/specs). See: https://github.com/ajv-validator/ajv/issues/1745

**Comment by essential-randomness** [comment]
I'd be very happy to have my PR picked up/used as inspiration! But it seems the issues I opened in the AJV repo haven't been closed yet, so I'm unsure what changed that made 3.1 work. Happy if that's the case, and looking forward to finally being able to use this library.

**Comment by seriousme** [comment]
Just a hint: [OpenApi schema validator](https://github.com/seriousme/openapi-schema-validator) works around the issue in AJV by using a modified version of the official schema in which the $dynamic refs have been replaced. (see https://github.com/seriousme/openapi-schema-validator/blob/master/test/convert-3.1.js)  This way it can still use AJV ;-)

The modified schema is available as: https://github.com/seriousme/openapi-schema-validator/blob/master/schemas/v3.1/schema.json

Hope this helps,
Hans

**Comment by thernstig** [comment]
@cdimascio @JacobLey looking at #713 it says it only partly solves this, not that it solves it completely. Can you re-open?

**Comment by JacobLey** [comment]
Agreed, 3.1 support should now be unblocked but is not yet implemented

Will hopefully get around to it in near future

**Comment by essential-randomness** [comment]
Thank you _so_ much for your hard work! Looking forward to 3.1 support in the future!

**Comment by btisdall** [comment]
Yes, many thanks Jacob.

**Comment by gonenduk** [comment]
Hi,
Any updates on this?
Really appreciate your efforts here!

**Comment by nexsodev** [comment]
2 years later... will nothing be done?

**Comment by kennyma-eplus** [comment]
`if-then-else` schema is quite important now
hope express validator can upgrade to 3.1 soon

**Comment by ahmed1hsn** [comment]
I can contribute the changes regarding this migration.

**Comment by itai-gendler** [comment]
really need this please

**Comment by rgAtos** [comment]
Hello, any news on this support ?
It's already needed, and we had to skip express-openapi-validator...

**Comment by kennyma-eplus** [comment]
any replacement of `express-openapi-validator` ? 
that need to support:
Open API 3.1 and ExpressJS

**Comment by Jackman3005** [comment]
From what I understand the core reason this library cannot support OpenAPI 3.1 is due to the underlying AJV library not yet supporting $dynamicRef features. This issue has been open on the AJV GitHub for awhile. I recently made a post and the suggestion still seems to be that `express-openapi-validator` should preprocess the spec and resolve dynamic references, as it is mentioned [here](https://github.com/ajv-validator/ajv/issues/1573#issuecomment-1862390739).

Can someone confirm that they agree the support should be added to this library instead of AJV?

Does anyone else know if there are any other reasons holding back support for OpenAPI Spec v3.1?

**Comment by SF97** [comment]
Hello
I've made the PR https://github.com/cdimascio/express-openapi-validator/pull/882 which should add support for OpenAPI 3.1, with @Jackman3005 suggestion. There are still tests missing, but I don't have a great amount of time to do them right now. I'm happy to take reviews/contributions to the PR to get OpenAPI 3.1 support as soon as possible :)

Happy 2024 everyone :partying_face:

**Comment by cdimascio** [comment]
This requires a tests. Contributions welcome.
I will plan to roll and alpha release, so folks can test it out

**Comment by Jackman3005** [comment]
An Alpha release to test with would be great!

**Comment by patricktyndall** [comment]
Hoping this is merged soon!

**Comment by cdimascio** [comment]
The alpha release is available for testing. see [comment](https://github.com/cdimascio/express-openapi-validator/pull/882#issuecomment-2308435082) in #882 

also called out in the [README](https://github.com/cdimascio/express-openapi-validator)

please provide feedback

**Comment by luisfidelis** [comment]
@cdimascio i submited a PR #1009 to also fix the ajv instance used in request validator.

**Comment by cdimascio** [comment]
initial oas3.1 support has been merged #1027 (includes #882)

**Comment by SF97** [comment]
Created PR https://github.com/apisyouwonthate/openapi.tools/pull/557 for https://openapi.tools/ to show support for version 3.1
