### ISSUE TITLE
Response validator not working when referencing same responses

### ISSUE THREAD

**Issue by crudo** [cdimascio/express-openapi-validator#576]
**Describe the bug**

It happens only if you have multiple responses referencing same file in multiple paths.

I have created a repo with this bug: https://github.com/crudo/express-openapi-validator-issue-2

Very similar to #553 but this time response validation is not working.

eg.

```
clusters > 200, 400
users > 200, 400
# 400 must reference the same response
```

---

Having:

```yaml
get:
  tags:
    - Users
  description: Returns a list of users
  operationId: getUsers
  responses:
    "200":
      $ref: "../responses/users.yaml"
    "400":
      $ref: "../responses/400.yaml"
```

This will fail:

```yaml
get:
  tags:
    - Clusters
  description: Returns a list of clusters
  operationId: getClusters
  responses:
    "200":
      $ref: "../responses/clusters.yaml"
    "400":
      $ref: "../responses/400.yaml"
```

This will NOT fail:

```yaml
get:
  tags:
    - Clusters
  description: Returns a list of clusters
  operationId: getClusters
  responses:
    "200":
      $ref: "../responses/clusters.yaml"
```

It will not fail, if you reference response only once:

```
clusters > 200, 400
users > 200
```

or

```
clusters > 200
users > 200, 400
```

**To Reproduce**

https://github.com/crudo/express-openapi-validator-issue-2

**Actual behavior** 

```
{
  "message": "Cannot read property 'content' of undefined"
}
```

**Expected behavior**

```
{
  "message": ".response should be array",
  "errors": [{
    "path": ".response",
    "message": "should be array",
    "errorCode": "type.openapi.validation"
  }]
}
```

**Examples and context**

https://github.com/crudo/express-openapi-validator-issue-2

**Comment by LarsV123** [comment]
Is there a fix/workaround for this? Having some trouble splitting my OpenAPI-spec into multiple files and I suspect this is the cause.

**Comment by crudo** [comment]
@LarsV123 Hey, looks like adding this to config solves my issue. https://github.com/cdimascio/express-openapi-validator#%EF%B8%8F-refparsermode-optional

```
$refParser: {
  mode: 'dereference',
},
```

**Comment by crudo** [comment]
@LarsV123 Hey, looks like adding this to config solves my issue. https://github.com/cdimascio/express-openapi-validator#%EF%B8%8F-refparsermode-optional

```
$refParser: {
  mode: 'dereference',
},
```
