### ISSUE TITLE
Missing list of additional properties, when additionalProperties error is thrown

### ISSUE THREAD

**Issue by medolino** [cdimascio/express-openapi-validator#58]
When additionalProperties validation fails, following error is thrown:

```js
{
   stack: 'Error: request.body should NOT have additional properties\n  at Object.POST-/api/....\n',
   message: 'request.body should NOT have additional properties',
   toJSON:[
      Function:toJSON
   ],
   status: 400,
   errors: [
      {
         path:'.body',
         message:'should NOT have additional properties',
         errorCode:'additionalProperties.openapi.validation'
      }
   ],
   name: 'Error',
   toString: [
      Function:toString
   ]
}
```

Is there any chance to add a list of additional properties to error message. It would be really helpfull to know, which properties should be removed from payload.

Information about additional properties is available in `validator.errors` array, generated by `ajv` validator (https://github.com/cdimascio/express-openapi-validator/blob/bc50cc0643ce3fe31962d366c80bb93a30804c06/src/middlewares/openapi.request.validator.ts#L139), but gets lost while creating customized error by calling `ajvErrorsToValidatorError` util function ( https://github.com/cdimascio/express-openapi-validator/blob/bc50cc0643ce3fe31962d366c80bb93a30804c06/src/middlewares/util.ts#L34).

Avj validation errors:

```js
[
   {
      keyword: 'additionalProperties',
      dataPath: '.body',
      schemaPath: '#/components/schemas/CreateItem/additionalProperties',
      params: {
         additionalProperty: 'invalidProperty'
      },
      message: 'should NOT have additional properties'
   }
]
```
Customized error object provided by `ajvErrorsToValidatorError`:
```js
{
   status:400,
   errors:[
      {
         path:'.body',
         message:'should NOT have additional properties',
         errorCode:'additionalProperties.openapi.validation'
      }
   ]
}
```

**Comment by cdimascio** [comment]
Yes we should definitely make this available.
I'm away until next week. I will plan to look at this then. If contributes something in the meantime I'll certainly have a look as well.

Thanks for the issue, @medolino

**Comment by cdimascio** [comment]
@medolino instead of making the change next week, it done now. check out v2.3.0

**Comment by medolino** [comment]
@cdimascio, it works great! Thanks for the quick response and resolution.
