### ISSUE TITLE
use with `discriminator` results in many '$ref: keywords ignored in schema at path "#"' messages

### ISSUE THREAD

**Issue by code-surfer** [cdimascio/express-openapi-validator#587]
As soon as I put a `discriminator` into my openapi spec, the program emits multiple 

    $ref: keywords ignored in schema at path "#"                                  

on startup. I guess it's not me doing it wrong, as the example behaves the same:
```
express-openapi-validator/examples/8-top-level-discriminator% npm start

> example@1.0.0 start .../express-openapi-validator/examples/8-top-level-discriminator
> node app.js

Listening on port 3000
$ref: keywords ignored in schema at path "#"
$ref: keywords ignored in schema at path "#"
^C
```

Is this just noise or does it indicate an error? According to a Web search the messages come from `ajv`.

**Comment by cdimascio** [comment]
@code-surfer this is just noise. as you mentioned. it's coming from AJV.
closing this out. nothing we can do here unfortunately.
