### ISSUE TITLE
Defaults in nested `oneOf` aren't being populated

### ISSUE THREAD

**Issue by kiahnjl** [cdimascio/express-openapi-validator#594]
**Describe the bug**
This only seems to be an issue when using `oneOf` nested inside a field or an array (i.e not at the top-level) AND where a `oneOf` subschema contains a field that uses a `default` value.

Under these circumstances, it seems like the `default` values aren't being populated automatically. This seems to happen even if a `discriminator` is used.

**To Reproduce**
Use `oneOf` to describe a field or array (Note: I have a proper example below) e.g
```
pet:
  oneOf:
    - $ref: '#/components/schemas/CatObject'
    - $ref: '#/components/schemas/DogObject'
```
Add a default value to one of the subschemas e.g
```
# DogObject
bark:
  type: boolean
  default: false
```

**Actual behavior** 
When POSTing to an endpoint using this spec, the `default` value for the field is not populated. 

**Expected behavior**
I would expect the `default` value to be populated, as this is the behavior using this field in other contexts.

**Examples and context**
I pushed up an example to a forked version of this repo, which you can use to see the changes I made ([see here](https://github.com/kiahnjl/express-openapi-validator/compare/master...kiahnjl:oneOf-defaults-issue?expand=1)) to test this out.

I was also unsure if this is related to [this comment here](https://github.com/cdimascio/express-openapi-validator/issues/104#issuecomment-751556105) about only supporting top-level discriminators. However, I wasn't sure because I'm not using discriminators in my example.

**Comment by cdimascio** [comment]
@kiahnjl the issue here is that this is not a top-level discriminator. currently, only top level is supported. I'm going to close this, as we've have other issues that account for it. i.e. https://github.com/cdimascio/express-openapi-validator/issues/104

work is needed to support nested discriminators

PRs are certainly welcome

**Comment by kiahnjl** [comment]
Thanks for confirming @cdimascio, that makes sense! I'll try and make some time to have a look :)
