### ISSUE TITLE
How to add additional middleware on routes handled by the 3.9 express-openapi-validator

### ISSUE THREAD

**Issue by davesargrad** [cdimascio/express-openapi-validator#633]
I use the [openapi-generator](https://github.com/OpenAPITools/openapi-generator). 

The generator creates an express app using the 3.9 version of the express-openapi-validator. It instantiates using the older "install" method (gone in 4.x). 

![image](https://user-images.githubusercontent.com/48793689/125585744-0b8ea7cb-41bf-4ea3-a3ef-931fcaa69d18.png)

I've been struggling (see [here](https://github.com/OpenAPITools/openapi-generator/issues/9917), and [here](https://stackoverflow.com/questions/68367824/how-to-access-the-api-key-inside-node-express-server-code-that-is-auto-generated)) to figure out how to add additional middleware on the routes handled by the express-openapi-validator in that generated server.

I cant simply change my application to use the 4.x version, since I dont want to have to rewrite a core piece of the auto-generated code.

As in [this video,](https://youtu.be/BnN3TQOG5-g?t=509) I need to get access to the API key in requests, and to add a check to my routes that ensures a user has an appropriate role.

With the 3.9 version of the validator how do I add an additional middleware (on the openapi routes of my application - _apiSpec_ in above) as in the following (verifyAccessToken)?

![image](https://user-images.githubusercontent.com/48793689/125582999-baca8360-56af-48e5-9613-1908c6c7ca21.png)

**Comment by davesargrad** [comment]
I think I am almost there. I found this ability to setup a security handler. 
![image](https://user-images.githubusercontent.com/48793689/125599445-e34591c1-10ed-45b2-b9f3-bd82737a866f.png)


However, the handler that I've defined is not called. I see the following error at my client application.

```
{
  "message": "a security handler for 'api_key' does not exist",
  "errors": [
    {
      "path": "/video/inventory",
      "message": "a security handler for 'api_key' does not exist"
    }
  ]
}
```

**Comment by davesargrad** [comment]
Omg!! I figured it out. The answer was staring me in the face. I didnt realize that I could use a custom key name. I thought the documentation suggested that the keys had to be one of several predefined values.

Btw.. you have created fairly excellent documentation. One of the best npm projects in that regard. 

![image](https://user-images.githubusercontent.com/48793689/125603315-25e72883-69ed-4951-a9a6-ed5bc0899f19.png)

**Comment by cdimascio** [comment]
@davesargrad glad u found the solution. Closing this out. Thanks for the issue
