### ISSUE TITLE
Whether Request Body is mandatory

### ISSUE THREAD

**Issue by huseyinozgul** [cdimascio/express-openapi-validator#646]
**Describe the bug**
If request body defined and it's not mandatory (required:false) and  the body is empty/null, bodyParser throws error "unsupported media type".

**To Reproduce**
Create a post request in the yaml
Define a schema in requestBodies, 
Set false this schema's required property. 

Then try to post your end point with out body

**Actual behavior** 
It throws an error like "unsupported media type"

**Expected behavior**
When body is not given and schema is not required , it should not throw an error.

**Examples and context**
requestBodies:
    search:
      description: A JSON object containing search parameters
      required: false
      content:
        'application/json':
          schema:
            $ref: '#/components/schemas/Search'

![image](https://user-images.githubusercontent.com/4598366/129441290-c7407739-9d95-47e4-a1a1-51e49393b03a.png)

**Comment by huseyinozgul** [comment]
You should update parsers/body.parse.ts  as below. I have no right to create new branch. 

![image](https://user-images.githubusercontent.com/4598366/129441691-d536190d-4f17-4d26-aefe-d8f9da2f4475.png)

**Comment by ArktinenKarpalo** [comment]
For this error to not occur, required must be explicitly set to false in openapi.yaml.
However, required defaults to false in openapi definition, so this should not be required.
Currently this error occurs if required is NOT set.
