### ISSUE TITLE
Validator does not work with express router

### ISSUE THREAD

**Issue by SpencerLawrenceBrown** [cdimascio/express-openapi-validator#65]
I am not sure if this is a feature request or a bug, but the validator does not validate requests and responses to/from express routers.

When I originally set up my app, all of my routes lived in the app.ts file and were being validated correctly.

`app.ts`
```
const app = express();
app.use(bodyParser.json());
app.use(express.json());

new OpenApiValidator({
  apiSpec: './workflow-tracker-openapi.yml',
  validateRequests: true,
  validateResponses: true,
}).install(app);

// Validates correctly! :)
app.get('/v1/progress/:workflowType', function(req, res, next) {
  res.json([{id: 1, name: 'test'}]);
});
```

however I am going to have a lot of routes + middlewares and want to use express routers to split them up. So I split my routes to use a router and the validator stopped working:

`app.ts`
```
const app = express();
app.use(bodyParser.json());
app.use(express.json());
app.use('/v1', progressRouter);

new OpenApiValidator({
  apiSpec: './workflow-tracker-openapi.yml',
  validateRequests: true,
  validateResponses: true,
}).install(app);
```

`api/progress.ts`
```
const router = express.Router();

// No longer validated :(
router.get('/progress/:workflowType', function(req, res, next) {
  res.json([{id: 1, name: 'test'}]);
});

export { router as progressRouter };
```

Furthermore I tried to install the routers to the `OpenApiValidator` but it only accepts `Applications`.

Am I missed a configuration step or are routers not supported currently? If they are not, is there timeline for when they would be supported?

Is there another workaround for this?

thank you!

**Comment by SpencerLawrenceBrown** [comment]
Looks like the validator middleware only gets pushed onto the app not the routes:

`express-openapi-validator/dist/index.js`
```
        if (this.options.validateRequests)
            use.push(validateMiddleware);
        if (this.options.validateResponses)
            use.push(resOav.validate());
        app.use(use);
```

I imagine this is the issue.

**Comment by SpencerLawrenceBrown** [comment]
ok wow, did more digging and it turns out that the order in which the middlewares are added matters
:(

`Validates correctly`
```
const app = express();
new OpenApiValidator({
  apiSpec: './workflow-tracker-openapi.yml',
  validateRequests: true,
  validateResponses: true,
}).install(app);
app.use(bodyParser.json());
app.use(express.json());
app.use('/v1', progressRouter);
```

`Does not validate`
```
const app = express();
app.use('/v1', progressRouter);
new OpenApiValidator({
  apiSpec: './workflow-tracker-openapi.yml',
  validateRequests: true,
  validateResponses: true,
}).install(app);
app.use(bodyParser.json());
app.use(express.json());
```

**Comment by SpencerLawrenceBrown** [comment]
Let me know if you'd like me to open up a pr to talk about this in the documentation

**Comment by cdimascio** [comment]
I believe the issue is the fact in the second example (Does not validate), the `bodyParser` middleware is set after the routes are installed.

Assuming this is the case, perhaps, a note should be added to the documentation.

Note that I can certainly have the validator install the middleware autoamtically, however I feel the choice of parser should be left to the user and not to the library.

I'm opne to suggestions.

**Comment by cdimascio** [comment]
@SpencerLawrenceBrown i've added some notes to the doc. feel free to provide feedback. thanks!

**Comment by JGoodenough** [comment]
@cdimascio I seem to be having the same trouble (it does not seem to be validating requests) however I am following the recommendations outlined above. Here's my code snippets, suggestions would be appreciated thanks!
