### ISSUE TITLE
Global security in spec must be an array

### ISSUE THREAD

**Issue by baranga** [cdimascio/express-openapi-validator#670]
**Describe the bug**
I'm adding global security definitions to my spec and the validator complaints about them in schema validation. I'm using the format documented in OpenAPI v3.0 (object with properties) but that fails. Instead I have to use an array of objects.

**To Reproduce**
Use this api spec to initialize the middleware:
```yaml
openapi: 3.0.3
info:
  version: 0.1.0
  title: Test

paths: {}

components:
  securitySchemes:
    bearer:
      type: http
      scheme: bearer

security:
  bearer: []
``` 

**Actual behavior** 
On starting my app I get this output:
```
>  openapi.validator: Validating schema
>  openapi.validator: validation errors [
>    {
>      "keyword": "type",
>      "dataPath": ".security",
>      "schemaPath": "#/properties/security/type",
>      "params": {
>        "type": "array"
>      },
>      "message": "should be array"
>    }
>  ]
```
I have to change my global security to make it work:
```yaml
# ...
security:
  - bearer: []
```

**Expected behavior**
It works with OpenAPI v3.0 compliant spec.

**Examples and context**
See above

**Comment by cdimascio** [comment]
@baranga thanks for the ticket. the spec states that`security` takes an array of `SecurityRequirementObject` not an object. The validation error provided is correct

> A declaration of which security mechanisms can be used across the API. The list of values includes alternative security requirement objects that can be used. Only one of the security requirement objects need to be satisfied to authorize a request. Individual operations can override this definition. To make security optional, an empty security requirement ({}) can be included in the array.

https://swagger.io/specification/
