### ISSUE TITLE
defaultResolver does not relate to default export

### ISSUE THREAD

**Issue by zzgab** [cdimascio/express-openapi-validator#671]
Hi! Great piece of work.

The `defaultResolver` seems to suggest that if the `operationId` symbol is not found in the exports, then it shall use `default`.

https://github.com/cdimascio/express-openapi-validator/blob/f295957b8d3356f519a1edc4fef7f0bf0002f876/src/resolvers.ts#L38

Yet, on the `return` statement, we no longer relate to a possible `default`, so the promised behaviour (to fall back to default export) does not happen.
https://github.com/cdimascio/express-openapi-validator/blob/f295957b8d3356f519a1edc4fef7f0bf0002f876/src/resolvers.ts#L47

Is there a reason for that?
Or shall I propose a PR?

Thanks

**Comment by cdimascio** [comment]
@zzgab this is bug. a PR will be fantastic. thank you!
