### ISSUE TITLE
Getting type error when accessing errorCode property of a ValidationErrorItem

### ISSUE THREAD

**Issue by shashanksapre** [cdimascio/express-openapi-validator#679]
**Describe the bug**
Getting a type error when I try to access properties of errors array within an error object of type `ValidationError`

**To Reproduce**
Access the property `errorCode` inside an `ValidationErrorItem`

**Actual behavior** 
`Type error: Property 'errorCode' does not exist on type 'ValidationErrorItem'. Did you mean 'error_code'.`
If I try to access error_code, it's undefined.

**Expected behavior**
Should be able to access errorCode as that's what is returned by express-openapi-validator
![image](https://user-images.githubusercontent.com/6241313/144409794-9f129064-60f4-499c-b917-77ebc6022f5b.png)

**Examples and context**
I'm trying to transform errors returned by validator into another standard error body response.

![image](https://user-images.githubusercontent.com/6241313/144409467-d6f9d4f6-9de2-4fab-a675-f82d97e0d3ba.png)

**Comment by reena-obc** [comment]
**Bug Description** 
Getting a Type Error when I try to access properties of errors array, if I try to access error_code, it's undefined. Type error: Property 'errorCode' does not exist on type 'ValidationErrorItem'. Did you mean 'error_code'.
![021802](https://user-images.githubusercontent.com/82019130/144422724-a484fb3e-7e84-4b55-adfc-4f6972910bf0.PNG)
