### ISSUE TITLE
Content-Type: multipart/form-data with the boundary

### ISSUE THREAD

**Issue by l-ko** [cdimascio/express-openapi-validator#7]
Getting:

Error: Unsupported Content-Type multipart/form-data; boundary=------------------------efe485372c5326e4

From:
curl -v -F title=1 http://localhost:3000/v1/route

Looks like a boundary parsing issue

**Comment by l-ko** [comment]
I see, this is from 'openapi-request-validator'. It is not clear from the description that 'openapi-request-validator' is used under the hood.

**Comment by cdimascio** [comment]
Thanks @l-ko. Are you able to provide an example? I’d like to reproduce it and have a look

**Comment by cdimascio** [comment]
@l-ko i was able to reproduce and i see the issue. The problem is actually do to the fact that body-parser doesn't handle multipart

from body-parser
>This does not handle multipart bodies, due to their complex and typically large nature. For multipart bodies, you may be interested in the following modules: ...

I will look into integrating multipart support into the validator. i plan to start with `multer` and perhaps later enable clients to bring there own.

**Comment by cdimascio** [comment]
@l-ko give version 0.53.3 a try. file upload should work
You can see an example [here](https://github.com/cdimascio/express-openapi-validator-example)

**Comment by yidongw** [comment]
@cdimascio what if you want to do use `operationHandlers` in the `OpenApiValidator` but still support `multipart`? I couldn't find a way to do it. I got the same error
