### ISSUE TITLE
Type Coercion Does Not Work for Boolean Parameters

### ISSUE THREAD

**Issue by YaakovR** [cdimascio/express-openapi-validator#702]
**Describe the bug**
When validating requests, parameters should be coerced according to [AVJ's type coercion rules](https://ajv.js.org/coercion.html#type-coercion-rules).

As a side issue, coercion from string to array happens even when `coerceTypes` is not explicitly set to `'array'`.

**To Reproduce**
1. git clone https://github.com/cdimascio/express-openapi-validator.git
2. npm run deps && npm i
3. cd express-openapi-validator/examples/1-standard
4. npm start

Enable coercion for requests in `app.js`:
```
validateRequests: {
  coerceTypes: true,
}
```

Add the following query parameter to `/pets` > `get` > `parameters`:
```
- name: boolParam
  in: query
  schema:
    type: boolean
```

`GET http://localhost:3000/v1/pets?type=dog&limit=20&boolParam=1`
`GET http://localhost:3000/v1/pets?type=dog&limit=20&boolParam=0`

**Actual behavior** 
```
{
    "message": "request.query.boolParam should be boolean",
    "errors": [
        {
            "path": ".query.boolParam",
            "message": "should be boolean",
            "errorCode": "type.openapi.validation"
        }
    ]
}
```

**Expected behavior**
As per AVJ's documention, 1 & 0 should be coerced as follows:
```
1 -> true
0 -> false
```

**Comment by cdimascio** [comment]
this is intentional to ensure numbers are treated as numbers and not coerced to boolean. although ajv supports this its not always desired to have input value that appears to be a number automatically converted from a number to a boolean.
