### ISSUE TITLE
additionalProperties should default to false (not true) even if undefined

### ISSUE THREAD

**Issue by zachweinberg** [cdimascio/express-openapi-validator#729]
**Describe the bug**
Right now if you define a route that does not have the `additionalProperties` key defined, the middleware will allow random properties to be sent to the route. This is a security risk. The only way to block these random properties is to not forget to set `additionalProperties: false`. As of today, it defaults to true when missing which is not safe. Users should have to explicitly allow additional properties in their schema.  

**To Reproduce**
1. Create a route in the API schema
2. Do not add `additionalProperties: boolean` to the route
3. Make a request to the route using a param that is not defined in the route
4. Observe that request is allowed

**Comment by cdimascio** [comment]
This current behavior is correct based on the OAS specification
`additionalProperties: true` 
https://swagger.io/docs/specification/data-models/data-types/#additionalProperties

closing at the behavior is spec-compliant

**Comment by fgblomqvist** [comment]
It's good that the validator is spec-compliant by default, but could it perhaps be an idea to add an option that changes this? Missing to set `additionalProperties: false` could lead to very annoying problems and setting it later on is a breaking change from an API perspective so it cannot "just be done".

Having something like a `defaultAdditionalProperties: false` would be fantastic!

**Comment by cdimascio** [comment]
Agreed. Adding an option to change the default has benefits. Please raise a PR. I suspect we'll want the option on both request and response validation options
