### ISSUE TITLE
Can't use multiple Media Types in combination with "multipart/form-data" in `requestBody.content`

### ISSUE THREAD

**Issue by medolino** [cdimascio/express-openapi-validator#74]
I am trying to create a route schema, which supports two requestBody contents (`application/json` and `multipart/form-data`). When I send `application/json` request, `unsupported media type` error is returned. `multipart/form-data` works ok.

I think the problem is in `isMultipart(req)` function, which does not predict that other content types might be present in schema configuration. (https://github.com/cdimascio/express-openapi-validator/blob/522c057ca4a16c06cb97f2f681b93f4d425ccbdc/src/middlewares/openapi.multipart.ts#L48) 

I think that `req.headers['content-type']` should also be checked together with `isMultipart(req)`.
https://github.com/cdimascio/express-openapi-validator/blob/522c057ca4a16c06cb97f2f681b93f4d425ccbdc/src/middlewares/openapi.multipart.ts#L8

Maybe this simple solution would solve this problem :)
```js
if (isMultipart(req) && isValidContentType(req)) {
      mult.any().......
}
```
In case of invalidContentType, unsupported media type error will be thrown later in code flow.

**Comment by cdimascio** [comment]
@medolino thanks so much for the issue and thanks for digging into the code. Feel free to submit a PR with your fix.
