### ISSUE TITLE
Returning status code 500 instead of 404 for routes without handler functions

### ISSUE THREAD

**Issue by JamesUnity3d** [cdimascio/express-openapi-validator#754]
**Describe the bug**
Openapi returns 500 if the route is namespace or the routes are partial of the full routes.

**To Reproduce**
```js
// this is an example pseudocode:

function controllerFoo() {
  const router = express.Router();

  router.get("/foo/:id", (req, res) => {
    res.send(`something...`);
  });

  return router;
}

const router = express.Router();
router.use('api', controllerFoo);
```

**Actual behavior** 
When the request route's path is `/api` or `/api/foo`, it will return 500 error. If the route's path is `/test` it will return 404 which is expected. If the route's path is `/api/foo/123` it will return expected data.

**Question**
Is there a way to config openapi to return status 404 for all the routes that are missing the handler function and all the namespace and partial routes?

**Comment by johandalabacka** [comment]
Maybe you set this as your last route:

```js
app.use('*', function(req, res) {
  return res.status(500)
});
```
