### ISSUE TITLE
Parameters declared by $ref are skipped

### ISSUE THREAD

**Issue by tom-inetum-realdolmen** [cdimascio/express-openapi-validator#803]
**Describe the bug**
Parameters that are declared as a $ref are skipped

**To Reproduce**
file openapi.yaml has this portion:

```yaml
openapi: 3.0.3
info:
  title: Parameter ReferenceObject
  description: test
  version: '1'
  termsOfService: https://www.google.be
  contact:
    email: noreply@test.com
security:
  - basicAuth: []
servers:
  - url: http://localhost
    description: local host
paths:
  /subject:
    get:
      summary: Test
      operationId: doTest
      parameters:
        - in: query
          name: firstParam
          schema: 
           type: string
        - $ref: "#/components/parameters/FromDateTime"
        - in: query
          name: secondParam
          schema:
            $ref: "/components/schemas/SecondParam"
      responses:
       ... (abbreviated for clarity)
components:
  schemas:
    SecondParam:
      type: string

  parameters:
    FromDateTime:
      in: query
      name: fromDateTime
      required: false
      schema: 
        type: string
```

**Actual behavior** 
parameter fromDateTime is present in `req.openapi.schema.parameters` but is not translated/parsed

**Expected behavior**
parameter fromDateTime is fully present in `req.openapi.schema.parameters`

**Examples and context**
see issue https://github.com/bug-hunters/oas3-tools/issues/59

**Comment by shashanksapre** [comment]
Same. I am having to define them inline for each endpoint. This goes for both path and query parameters. :(

**Comment by duncanbeevers** [comment]
This was failing for me in v5.3.1, but is working in v.5.3.3.
I believe https://github.com/cdimascio/express-openapi-validator/issues/808 also fixes this.

**Comment by cdimascio** [comment]
@tom-inetum-realdolmen the provided spec appears to have errors
for instance,
`     $ref: "/components/schemas/SecondParam"` is missing the `#` 
and should be 
`     $ref: "/components/schemas/SecondParam"`

can you retry with the fix

**Comment by duncanbeevers** [comment]
I'm reproducing this error locally, and have traced it to the behavior of `ajv` when validating + coercing types at https://github.com/cdimascio/express-openapi-validator/blob/master/src/middlewares/openapi.request.validator.ts#L188

I have a reproduce case, but since I think it needs fixing upstream I'm holding off on a PR.
However, I'll see if I can stick a pin in it today.

**Comment by duncanbeevers** [comment]
@shashanksapre I didn't see anything while fixing this bug that indicated it should affect query parameters.
When I extended the test case here with a numeric query parameter it came through in `req.query` coerced to the correct type, as expected.

Please ping me if you're still seeing this issue affecting query parameters, after applying this fix.
