### ISSUE TITLE
Creating multiple app instances causes spec read to be empty

### ISSUE THREAD

**Issue by charlocharlie** [cdimascio/express-openapi-validator#81]
While writing unit tests for an express app, I kept seeing the error `version missing from OpenAPI specification` when creating multiple Express app instances within one Jest test file.

After some debugging, it looks like the root cause is [loadSpecFile](https://github.com/cdimascio/express-openapi-validator/blob/master/src/framework/util.ts#L31) not throwing an error when performing `require(absolutePath)`. This returns an object just containing `__proto__`, which lets it past all the null checks until it hits the version missing error.

### How to reproduce

- Clone my demo repo: https://github.com/charlocharlie/open-api-validator-test
- `npm i`
- `npm run test`
- Observe error on second test: `version missing from OpenAPI specification`

Just creating multiple app instances in `index.js` didn't seem to cause the bug. It may have something to do with how Jest sets up its tests. Using `jest --runInBand` to run the tests in series doesn't fix this.

**Comment by cdimascio** [comment]
Thanks for the issue @charlocharlie. The reproducible project is much appreciated.  will have a look

**Comment by cdimascio** [comment]
I think i see the issue, should have a fix soon

**Comment by cdimascio** [comment]
@charlocharlie, please give v2.8.1 a try. it should fix the issue described. thanks!
