### ISSUE TITLE
Support for Dynamic OpenAPI Specs (`"servers": [{"url": "/"}]`)

### ISSUE THREAD

**Issue by sennyeya** [cdimascio/express-openapi-validator#843]
**Is your feature request related to a problem? Please describe.**
Before I jump in, thanks for this library, it's really great!  I'm working on adding OpenAPI request validation to [Backstage](https://github.com/backstage/backstage) and found this library. Basically, Backstage has a routing system that decouples the parent route from the plugin. Each plugin can be mounted at different routes for different implementations so a full Backstage spec has to be dynamic. See [this](https://github.com/backstage/backstage/blob/ffec81febf07854ef896c4e00fb0ca5a3ecb0353/packages/backend/src/index.ts#L166).

To support that dynamic nature, each plugin has a spec with a 
```
servers:
  - url: '/'
```
section (you can see an example [here](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/schema/openapi.yaml#L13)). Those specs can then be combined with routing knowledge at run time to create a tailored "Backstage" full API spec. However, my goal is to support per plugin validation that's decoupled from the full API spec. Plugin owners could then opt into validation and configure it themselves. Ideally, this library would be what we use for that. However, I'm getting issues from [this line](https://github.com/cdimascio/express-openapi-validator/blob/01950b7558209a6ecefeea5699d5a30c05023662/src/middlewares/openapi.metadata.ts#L67C5-L68). The `req.originalUrl` will always contain the full URL with all of the parent routers, meaning it's not possible to validate against a router specific spec.

**Describe the solution you'd like**
A toggle to use `req.path` or `req.url` instead of `req.originalUrl`. Basically, the ability to turn off the functionality introduced in #211 to support fully context aware routers.

**Describe alternatives you've considered**
I also looked at #113, but I think this is a separate use case with a similar soluiton.

**Additional context**

**Comment by cdimascio** [comment]
Yes. A PR for this is welcome. Thanks!

**Comment by cdimascio** [comment]
the new `useRequestUrl` option is available in v5.1.0. Set `useRequestUrl: true` in the validator options

See PR https://github.com/cdimascio/express-openapi-validator/pull/857

**Comment by cdimascio** [comment]
v
