### ISSUE TITLE
Add support to multiple specs on the same routes

### ISSUE THREAD

**Issue by naor10** [cdimascio/express-openapi-validator#859]
**Is your feature request related to a problem? Please describe.**
Cannot manage to apply to the same routes multiple specs.

**Describe the solution you'd like**
apiSpec prop would have the ability to get an array of paths.

**Describe alternatives you've considered**
I tried to manually merge the files into one file.

**Comment by cdimascio** [comment]
To accommodate this the path must differ e.g. /v1 and /v2. Using the same path will expectedly result in conflicts
