### ISSUE TITLE
Type coercion stops working if request validation is turned off

### ISSUE THREAD

**Issue by renke0** [cdimascio/express-openapi-validator#884]
**Describe the bug**
I've noticed query parameters not being coerced to the correct type when the request validation is set to false. Setting `coerceTypes` in either of the two places shown below didn't seem to have any effect.

```typescript
middleware({
  validateRequests: { coerceTypes: true },
  coerceTypes: true
})
```
So far I noticed the error with query parameters only, but I am not sure if this is reproducible in other places.

**To Reproduce**
Disable `validateRequests` in your middleware config and try to use an endpoint that has a query parameter with a type different than string.

**Actual behavior** 
The query parameter type will always be string when `validateRequests` is off.

**Expected behavior**
The query parameters to be coerced to the correct types

**Examples and context**
```yaml
openapi: 3.0.1
info:
  version: 1.0.0
  title: test
paths:
  /cars:
    get:
      parameters:
        - name: include_all
          in: query
          schema: 
            type: boolean
      responses:
        200:
          description: OK
````

Making a `GET /cars?include_all=true` will trigger the correct operation handler, but the `include_all` variable will be a string.

**Comment by cdimascio** [comment]
Coerce types opt external to validateRequests is legacy. The opt was moved into validateRequests for clarity. It is retained in for backward compat
