### ISSUE TITLE
Support for the HyperExpress web framework

### ISSUE THREAD

**Issue by MarcErdmann** [cdimascio/express-openapi-validator#886]
**Is your feature request related to a problem? Please describe.**
Express.js was one of the first Node.js web frameworks and has wide adoption still. But since its release many other web frameworks have been released – some with significant higher performance. Therefore, it is great to see that this project already supports Koa, NestJS, and Fastify in addition to express. However, looking at the "TechEmpower Web Frameworks Benchmark" [latest results for web frameworks running on Node.js](https://www.techempower.com/benchmarks/#hw=ph&test=composite&section=data-r22&p=zik0zj-zijocf-zik0zj-zik0zj-zik0zj-sf), it is clear to see that all of those frameworks are outperformed by [HyperExpress](https://github.com/kartikk221/hyper-express). Another reason to consider supporting HyperExpress is that it aims to be in parts compatible with express.js and therefore being a better framework to switch to for companies using express.js than switching to e.g. Fastify.

**Describe the solution you'd like**
I would like to see official support for HyperExpress.

**Describe alternatives you've considered**
Alternatively, I can continue using express.js for some time, or write my own OpenAPI validator for HyperExpress using AJV.

**Comment by cdimascio** [comment]
This is not currently planned. I am open to a PR however
