### ISSUE TITLE
Subsequent express middleware not invoked after OpenApiValidator

### ISSUE THREAD

**Issue by dieseldjango** [cdimascio/express-openapi-validator#908]
**Describe the bug**
I have an express server that is configured with multiple middleware, including some before the openapi validator and some after, such as:
```
app.use(someMiddleware);
app.use(openApiValidator);
app.use(someOtherMiddleware);
```
When running the app the middleware registered after my OpenApiValidator instance is never getting called. 
Is this to be expected? I was expecting that the validator would register express routes and would otherwise just call the next middleware in the chain.

**To Reproduce**
Setup as described below, write to console or set a breakpoint in `someOtherMiddleware`, start your server, send a request to one of the openapi endpoints.

**Actual behavior** 
The `someOtherMiddleware` function is not called.

**Expected behavior**
The `someOtherMiddleware` function should be called.

**Examples and context**
Here's an example of what the config is like:
```
const openApiValidator = OpenApiValidator.middleware({
  apiSpec: OpenApiSpec,
  validateRequests: true,
  validateResponses: true,
  ignorePaths: (path: string) => !/^\/api/.test(path),
  operationHandlers: {
    basePath: "unused",
    resolver: (_basePath, route, apiDoc) => {
      const schema = apiDoc.paths[route.openApiRoute][route.method.toLowerCase()];
      const moduleName = schema["x-eov-operation-handler"];
      const functionName = schema["operationId"];
      const mod = openApiHandlers[moduleName];
      if (!mod) {
        throw new InternalServerError(
          `Could not find handler module "${moduleName}" for method "${route.method}" of route "${route.openApiRoute}"`
        );
      }
      const func = mod[functionName];
      if (func === undefined) {
        throw new Error(`Could not find function "${functionName}" in module "${moduleName}"`);
      }
      return func;
    },
  },
  validateSecurity: {
    handlers: {
      BearerAuth: openApiBearerTokenAuthHandler,
    },
  },
});
```

**Comment by JeffJassky** [comment]
I can second this. Experiencing the same issue.

**Comment by JeffJassky** [comment]
@dieseldjango if you need subsequent middleware to run, you need to make sure you return a valid express `RequestHandler` in the resolver method.

That means your `openApiHandlers[moduleName][functionName]` must return a `function (req, res, next){...}` and within that handler, you need to call the `next()` function.

For example, request handlers should operate like this:
```javascript
openApiHandlers.module.funcName = function handler(req, res, next){
  console.log('Handling the operation)
  next() <- this is what will forward the request to the next middleware
}
```

If you want subsequent middleware to run in the case of an `InternalServerError`, or in the case that `func === undefined`, you'll also need to return a function(req, res, next){...}

For example:
```javascript
...
      if (!mod) {
        // return a request handler
        return (req, res, next) => {
          // Create your error without throwing it
          const error = new InternalServerError(
            `Could not find handler module "${moduleName}" for method "${route.method}" of route "${route.openApiRoute}"`
          )
          next(error) // call the next(), passing the error as the argument
        }
      }
      const func = mod[functionName];
      if (func === undefined) {
        return (req, res, next) => {
          // Create your error without throwing it
          const error = new Error(`Could not find function "${functionName}" in module "${moduleName}"`);
          next(error) // call the next(), passing the error as the argument
        }
    }
...
```

**Comment by dieseldjango** [comment]
Thanks. I'll make sure to call `next()` in the route handler. However, in this case I want my middleware to run after the auth handler registered in `validateSecurity` but before the route handler. I can accomplish what I need by creating a wrapper for my route handlers, but I was hoping there'd be some way to register middleware.
