### ISSUE TITLE
Discriminator support

### ISSUE THREAD

**Issue by frejonb** [cdimascio/express-openapi-validator#95]
Do you support validation against the discriminator spec https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#discriminatorObject ?

**Comment by cdimascio** [comment]
To quote Evgeny

> I may be wrong, but I think in OpenAPI v3 you must use oneOf, discriminator is just to inform the tools what is the logic behind these oneOfs. My understanding is that removing discriminator in v3 should always result in the same validation outcome (valid/invalid), but may affect error reporting or some other behaviours. So from validation point of view it can be just ignored.

Assuming this is the case, then yes. express-openapi-validator does have support for `oneOf`

**Comment by frejonb** [comment]
Fair enough
