### ISSUE TITLE
Unhandled async exceptions in validator middleware(s)

### ISSUE THREAD

**Issue by gonenduk** [cdimascio/express-openapi-validator#96]
Issue #90 made me wonder a little how come I didn't get any reply from the package when there was an exception thrown during the (security) validations. Express.js does catch every exception and calls next with the exception error. Why didn't my error handler got called with the exception?
The only cases Express.js doesn't catch - are exceptions thrown in an async operation. I went and check the code of this package and indeed the middlewares used here are async. Express.js cannot handle async exceptions as it doesn't have the context.
More about express error handling can be found here: [error handling](https://expressjs.com/en/guide/error-handling.html)
So what happens when an unhandled async exception is thrown during a middleware? Two things:
1. The client doesn't get a reply and hangs until a timeout is reached.
2. Node.js itself catches the unhandled async exception (node-1904). However, this "catch" is deprecated and in future versions will be removed, meaning the process will exit.
Since we want to use the validator in production - we cannot let it hang the response to the client or make the process exit. We have to catch every exception - even if it's caused by an unknown bug. We have to be on the safe side, just in case.

So what do we need to do? Easy, just wrap every middleware we return (security, validation and so on) with a Promise.resolve().then(() => try {...original code...} catch (next))
A nicer way is to have a function defined in one place that wraps all the middlewares we return.
More about this solution can be found here: [async error handling](https://medium.com/@Abazhenov/using-async-await-in-express-with-node-8-b8af872c0016)

I tried this solution on the previous version with the hang - and it worked! I got an error in my error handler and I could return a server error to my client.
I believe we should use this wrapper function to make our middlewares safe as we want to use the validation in production environments. It's alway better to return 500 server error than to not return at all and let node terminate/handle it for us.

I would do the PR myself, but again - I am not a TypeScript person, so I do not know how to add the wrapper function to the utils file and make it export. So I guess someone else can do it - if you decide this is required.

**Comment by cdimascio** [comment]
Thanks. Can you provide an example of this suggestion. I'll look at be integrating it into the package.

**Comment by cdimascio** [comment]
There are a few places I throw. It may be that these need to be changed to `return next(err)` rather than `throw err`

**Comment by gonenduk** [comment]
You should be able to always throw, as you work with async functions and a throw is actually a rejected promise, you only need to be able to catch them and convert to next(error). Also, in case of bugs, like we had with the security issue checking undefined path, an exception will be thrown anyway...
For your tests, try to install version 2.12.1 which had the bug. Call an undefined path and you will see the unhandled exception.
Now in openapi.security.js in line 6 where you return a middleware, change it to:
`
return async (req, res, next) => {
  Promise.resolve().then(() => {
    original content of function...
  }.catch(next);
}
`
and run again. This time it's not an unhandled exception but next(error) is called. The exception is caught and goes into the express error handler.

**Comment by gonenduk** [comment]
You can also create in middleware/utils.js a new exported function called safe, like this (sorry I don't use TypeScript format):
`
const safe = (fn) => (req, res, next) => {
  Promise.resolve(fn(req, res, next)).catch(next);
};
`
And then use this function everywhere you return a middleware, like in openapi.security.js line 6:
`
return safe(async (req, res, next) => { original content of function... })
`
Which is much cleaner.

**Comment by gonenduk** [comment]
Before we move on with this - I found a dead simple library which replaces the need to wrap each and every route with the catch(next).
Let me test it and get back to you!
[express-async-errors](https://www.npmjs.com/package/express-async-errors)

**Comment by gonenduk** [comment]
Ok, it works very well. However, it is a one place where you change the behaviour of the entire express lib of the running process... so it's not up to the validator to do it - not using this easy way.
I am closing this issue for now as it is less urgent. Whoever wants to protect his middlewares (and the validator middlewares) can do it.
